import { useEffect, useState } from 'react';
import { growthService } from '@/services/growth/growth.service';
import { authenticatedApi } from '@/lib/authenticated-api';
import type { GrowthRecord } from '@/types/growth';
type Row={platform:string|null;campaign_id:string|null;content_item_id:string|null;tracked_link_id:string;campaign_name:string|null;content_title:string|null;link_label:string;visits:number;unique_signups:number;converted_visits:number};
type Report={rows:Row[];unattributed_company_signups:number;limitation:string;qualification:string};
const panel='my-6 rounded-2xl border border-white/15 bg-white/[.035] p-5 text-white';
const control='mt-1 w-full rounded border border-white/25 bg-white p-2 text-white';
export function ContentTrackedLinks({items}:{items:GrowthRecord[]}) {
 const [campaigns,setCampaigns]=useState<GrowthRecord[]>([]),[links,setLinks]=useState<GrowthRecord[]>([]),[content,setContent]=useState(''),[campaign,setCampaign]=useState(''),[platform,setPlatform]=useState(''),[label,setLabel]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 useEffect(()=>{void Promise.all([growthService.list('campaigns'),growthService.trackedLinks()]).then(([c,l])=>{setCampaigns(c);setLinks(l);}).catch(()=>setError('Tracked links could not be loaded.'));},[]);
 const selected=items.find(i=>i.id===content);
 return <section className={panel} aria-label="Content acquisition links"><h2 className="font-bold">Content → waitlist link</h2><p className="mt-2 text-sm text-white/65">Bind a new link to saved content and its campaign. Creation never publishes. Use the link in the approved platform copy; visit lineage is fixed when recorded.</p>
 <div className="mt-4 grid gap-3 sm:grid-cols-2"><label>Content<select className={control} value={content} onChange={e=>{setContent(e.target.value);const i=items.find(i=>i.id===e.target.value);setCampaign(String(i?.campaign_id??''));setPlatform(['linkedin','facebook','instagram','tiktok','x','snapchat'].includes(String(i?.platform))?String(i?.platform):'');}}><option value="">Choose saved content</option>{items.map(i=><option key={i.id} value={i.id}>{String(i.title)}</option>)}</select></label>
 <label>Campaign<select className={control} value={campaign} disabled={Boolean(selected?.campaign_id)} onChange={e=>setCampaign(e.target.value)}><option value="">Unknown / no campaign</option>{campaigns.map(c=><option key={c.id} value={c.id}>{String(c.name)}</option>)}</select></label>
 <label>Platform<select className={control} value={platform} onChange={e=>setPlatform(e.target.value)}><option value="">Select actual platform</option>{['linkedin','facebook','instagram','tiktok','x','snapchat'].map(p=><option key={p}>{p}</option>)}</select></label><label>Link label<input className={control} value={label} maxLength={200} onChange={e=>setLabel(e.target.value)}/></label></div>
 {error&&<p role="alert" className="mt-3 text-red-800">{error}</p>}{notice&&<p role="status" className="mt-3 text-green-800">{notice}</p>}
 <button className="mt-4 rounded border border-white/30 px-4 py-2 disabled:opacity-40" disabled={busy||!content||!platform||!label.trim()} onClick={async()=>{setBusy(true);setError('');try{const link=await growthService.createTrackedLink({label:label.trim(),destination_url:'https://klps.co.uk/waitlist',source:platform,medium:'social',content_item_id:content,campaign_id:campaign||null,campaign:campaigns.find(c=>c.id===campaign)?.name??null});setLinks(l=>[link,...l]);setNotice('Link created. Copy it into the content you will review.');}catch(e){setError(e instanceof Error?e.message:'Link could not be created.');}finally{setBusy(false);}}}>Create bound waitlist link</button>
 <ul className="mt-4 space-y-3">{links.filter(l=>l.content_item_id&&(!content||l.content_item_id===content)).map(l=><li className="break-all text-sm" key={l.id}><strong>{String(l.label)}</strong><div>{String(l.generated_url)}</div><button className="underline" onClick={()=>void navigator.clipboard.writeText(String(l.generated_url)).then(()=>setNotice('Link copied.')).catch(()=>setError('Copy unavailable; select the link text manually.'))}>Copy link</button></li>)}</ul></section>;
}
export function AcquisitionReport() {
 const [report,setReport]=useState<Report|null>(null),[error,setError]=useState('');
 const load=async()=>{try{setReport((await authenticatedApi<{acquisition:Report}>('/api/growth/acquisition')).acquisition);setError('');}catch{setError('Acquisition reporting could not be loaded.');}};
 useEffect(()=>{void load();},[]);
 const [group,setGroup]=useState<'link'|'platform'|'campaign'|'content'>('link');
 const groups=new Map<string,Row>();
 for(const r of report?.rows??[]){const key=group==='link'?r.tracked_link_id:group==='platform'?r.platform:group==='campaign'?r.campaign_id:r.content_item_id;const id=key??'unknown';const old=groups.get(id);groups.set(id,old?{...old,visits:old.visits+r.visits,unique_signups:old.unique_signups+r.unique_signups,converted_visits:old.converted_visits+r.converted_visits}:{...r});}
 return <section className={panel} aria-label="Waitlist acquisition"><h2 className="font-bold">Waitlist acquisition · first-party evidence</h2><p className="mt-2 text-sm text-white/65">All time. Consent-based first-touch attribution; qualification is a separate community assessment. Existing manual metric snapshots do not contribute to these counts.</p><div className="my-3 flex gap-3"><label>Group by <select className="bg-white p-2" value={group} onChange={e=>setGroup(e.target.value as typeof group)}>{['link','platform','campaign','content'].map(g=><option key={g}>{g}</option>)}</select></label><button className="underline" onClick={()=>void load()}>Refresh acquisition</button></div>
 {error&&<p role="alert" className="text-red-800">{error}</p>}{report&&<><p className="mb-3 text-sm">Company-wide unknown/unattributed signups: <strong>{report.unattributed_company_signups}</strong> (includes historical records).</p><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{[group==='link'?'Link · platform · campaign · content':group,'Visits','Unique signups','Visit conversion'].map(h=><th className="p-2" key={h}>{h}</th>)}</tr></thead><tbody>{[...groups.entries()].map(([id,r])=><tr key={id} className="border-t border-white/10"><td className="p-2">{group==='link'?`${r.link_label} · ${r.platform??'Unknown'} · ${r.campaign_name??'Unknown campaign'} · ${r.content_title??'Unknown content'}`:group==='platform'?r.platform??'Unknown':group==='campaign'?r.campaign_name??'Unknown campaign':r.content_title??'Unknown content'}</td><td className="p-2">{r.visits}</td><td className="p-2">{r.unique_signups}</td><td className="p-2">{r.visits?`${(100*r.converted_visits/r.visits).toFixed(1)}%`:'—'}</td></tr>)}</tbody></table></div>{!report.rows.length&&<p>No consented tracked visits yet.</p>}<p className="mt-3 text-xs text-white/60">{report.limitation} Repeat email submissions never create new acquisitions. A converted visit contains at least one new signup; multiple people may share a session.</p></>}
 </section>;
}
