import {ProductionStudio,ProductionPreview} from './ProductionStudio';
import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {authenticatedApi,authenticatedBlob} from '@/lib/authenticated-api';
import {growthService} from '@/services/growth/growth.service';
type Asset={id:string;display_name:string;provenance_kind:string;provenance_notes:string|null;approved_for_use:boolean;mime_type:string|null;aspect_ratio:string|null;duration_seconds:number|null;suitable_platforms:string[]};
type Brief={slot:string;platform:string;role:string;order:number;title:string;included:boolean;review:string;approach:string;cta:string;execution:string;talking_points:string[];structure?:string[];asset_id:string|null;requirement:{kind:string;media_type:string;aspect_ratio:string;duration_seconds:number|null;topic:string;deadline:string}};
type Content={production_state?:{asset_id:string|null;candidates:{id:string;media_asset_id?:string;rejected_at?:string|null}[]};id:string;title:string;platform:string;scheduled_at:string;platform_brief:Brief;asset_ready:boolean;suggested_assets:Asset[]};
type Editable=Content&Brief&{topic?:string};
type Plan={id:string;name:string;objective:string;audience:string;narrative_opportunity_id:string;planning_version:number;planning_approved_at:string|null;current:boolean;items:Content[];narrative_plan:{theme:string;constraints:string;source_insight_id:string;evidence:{source_path:string}}};
type Opportunity={id:string;status:string;current:boolean;proposal:{title:string}};
type Campaign={id:string;name?:unknown;narrative_plan?:unknown};
type PlanData={plans:Plan[];media:Asset[]};
type Timeline={plans:Plan[];manual:{id:string;starts_at:string;title:string;entry_type:string;status:string}[];ordinary:{id:string;scheduled_at:string;title:string}[];execution:{id:string;scheduled_for:string;provider:string;status:string;content_item_id:string}[]};
const platforms=['linkedin','facebook','instagram','x','tiktok','snapchat'];
const roles=['awareness','education','credibility_nurture','founder_build_journey','conversion'];
const btn='rounded-lg border border-slate-400 bg-white px-3 py-2 text-sm text-slate-900 disabled:opacity-40';
const field='w-full rounded border border-slate-400 bg-white p-2 text-sm text-slate-900';
const words=(s:string)=>s.replaceAll('_',' ');
function PlanEditor({plan,reload}:{plan:Plan;reload:()=>Promise<void>}){
 const [newPlatform,setNewPlatform]=useState('');
 const [objective,setObjective]=useState(plan.objective??''),[audience,setAudience]=useState(plan.audience??''),[theme,setTheme]=useState(plan.narrative_plan.theme??'');
 const [items,setItems]=useState<Editable[]>([...plan.items].sort((a,b)=>a.platform_brief.order-b.platform_brief.order).map(i=>({...i,...i.platform_brief}))),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const change=(id:string,patch:Partial<Editable>)=>setItems(v=>v.map(i=>i.id===id?{...i,...patch}:i));
 const move=(index:number,delta:number)=>setItems(v=>{const next=[...v],j=index+delta;if(j<0||j>=next.length)return v;const date=next[index].scheduled_at;next[index]={...next[index],scheduled_at:next[j].scheduled_at};next[j]={...next[j],scheduled_at:date};[next[index],next[j]]=[next[j],next[index]];return next;});
 const save=async(approve:boolean)=>{setBusy(true);setError('');try{await authenticatedApi(`/api/growth/narrative-plans/${plan.id}`,{method:'PATCH',body:JSON.stringify({version:plan.planning_version,items,approve,objective,audience,theme})});await reload();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const grid=items.filter(i=>i.platform==='instagram').sort((a,b)=>Date.parse(a.scheduled_at)-Date.parse(b.scheduled_at)||items.indexOf(a)-items.indexOf(b)).reverse();
 return <article id={`plan-${plan.id}`} className="my-5 rounded-xl border border-slate-300 bg-white p-4 text-slate-900"><h3 className="text-lg font-bold">{plan.name}</h3><div className="my-3 grid gap-2 sm:grid-cols-3"><label>Objective<input className={field} value={objective} onChange={e=>setObjective(e.target.value)}/></label><label>Audience<input className={field} value={audience} onChange={e=>setAudience(e.target.value)}/></label><label>Narrative theme<input className={field} value={theme} onChange={e=>setTheme(e.target.value)}/></label></div><p className="text-sm">{words(plan.narrative_plan.theme)} · {words(plan.audience??'')} · {plan.planning_approved_at?'Sequence approved for planning':'Draft sequence'}{!plan.current?' · SOURCE NEEDS REVIEW':''}</p><p className="mt-2 text-sm">Evidence boundary: {plan.narrative_plan.constraints}</p><Link className="text-sm underline" to={plan.narrative_plan.evidence.source_path} target="_blank" rel="noopener noreferrer">Inspect canonical evidence</Link><p className="text-xs">Insight: {plan.narrative_plan.source_insight_id}. Planning approval never approves a social post.</p>
 {grid.length>0&&<div className="my-4"><h4 className="font-semibold">Instagram 3×3 preview</h4><p className="mb-2 text-sm">Newest planned position first, as a profile grid. Six designed positions and three genuine-media reservations. Excluded positions remain visible as gaps.</p><div className="grid grid-cols-3 gap-2">{grid.map(i=><div key={i.id} className={`min-h-28 rounded border p-2 text-xs ${i.requirement.kind==='genuine'?'border-teal-600 bg-teal-50':'border-purple-300 bg-purple-50'}`}><strong>{i.slot} · {i.included?'Included':'Excluded'}</strong><p>{words(i.role)}</p>{i.production_state?.candidates.find(c=>c.id===i.production_state?.asset_id&&!c.rejected_at)?.media_asset_id&&<ProductionPreview assetId={i.production_state.candidates.find(c=>c.id===i.production_state?.asset_id)!.media_asset_id!} video={i.requirement.media_type==='video'}/>}<p className="mt-2">{i.requirement.kind==='genuine'?'Genuine media required':'Designed / generated asset brief'}</p><p>{new Date(i.scheduled_at).toLocaleDateString('en-GB')}</p></div>)}</div></div>}
 <div className="my-3 flex flex-wrap items-center gap-2"><label>Add platform briefs<select className={field} value={newPlatform} onChange={e=>setNewPlatform(e.target.value)}><option value="">Choose an additional platform</option>{platforms.filter(p=>!items.some(i=>i.platform===p)).map(p=><option key={p}>{p}</option>)}</select></label><button className={btn} disabled={busy||!plan.current||!newPlatform} onClick={async()=>{setBusy(true);setError('');try{await authenticatedApi(`/api/growth/narrative-plans/${plan.id}/platforms`,{method:'POST',body:JSON.stringify({version:plan.planning_version,platforms:[newPlatform]})});await reload();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Add pending briefs to this sequence</button><p className="text-xs">Save existing edits first. Adding briefs requires review and approval of the sequence again.</p></div><p className="my-3 text-sm">Edit the sequence, accept or reject each brief, and save. Asset origin and genuine-media requirements cannot be replaced by changing copy.</p>
 <div className="space-y-3">{items.map((i,index)=><details key={i.id} className="rounded border border-slate-300 p-3"><summary className="cursor-pointer font-medium">{index+1}. {i.platform} · {words(i.role)} · {new Date(i.scheduled_at).toLocaleDateString('en-GB')} · {i.asset_ready?'Asset ready':i.suggested_assets.length?'Reuse available':'Asset needed'} · {i.review}</summary><div className="mt-3 space-y-3"><div className="flex flex-wrap gap-2"><button className={btn} disabled={busy||index===0} onClick={()=>move(index,-1)}>Move earlier</button><button className={btn} disabled={busy||index===items.length-1} onClick={()=>move(index,1)}>Move later</button><label><input type="checkbox" checked={i.included} onChange={e=>change(i.id,{included:e.target.checked})}/> Include this item</label></div>
 <label className="block text-sm">Brief title<input className={field} value={i.title} onChange={e=>change(i.id,{title:e.target.value})}/></label>
 <div className="grid gap-3 sm:grid-cols-2"><label>Purpose<select className={field} value={i.role} onChange={e=>change(i.id,{role:e.target.value})}>{roles.map(r=><option key={r}>{r}</option>)}</select></label><label>Intended date (UTC)<input type="datetime-local" className={field} value={new Date(i.scheduled_at).toISOString().slice(0,16)} onChange={e=>e.target.value&&change(i.id,{scheduled_at:new Date(e.target.value+'Z').toISOString()})}/></label></div>
 <label className="block text-sm">Platform-native brief<textarea className={field} rows={3} value={i.approach} onChange={e=>change(i.id,{approach:e.target.value})}/></label><label className="block text-sm">CTA intention<textarea className={field} value={i.cta} onChange={e=>change(i.id,{cta:e.target.value})}/></label>
 <ul className="list-inside list-disc text-sm">{i.structure?.map((step:string)=><li key={step}>{step}</li>)}</ul><p className="text-sm">Action: {words(i.execution)}. No execution is triggered by this plan.</p><label className="block text-sm">Suggested talking points (one per line)<textarea className={field} value={i.talking_points.join('\n')} onChange={e=>change(i.id,{talking_points:e.target.value.split('\n')})}/></label>
 {i.requirement.media_type!=='none'&&<div className="rounded bg-slate-100 p-3 text-sm"><strong>{i.requirement.kind==='genuine'?'Emma needed — genuine media':'Asset brief'}</strong><p>{i.requirement.media_type} · {i.requirement.aspect_ratio} {i.requirement.duration_seconds?`· approximately ${i.requirement.duration_seconds} seconds`:''}</p><label className="block">Media topic<input className={field} value={i.topic??i.requirement.topic} onChange={e=>change(i.id,{topic:e.target.value})}/></label><p>Needed by {new Date(i.requirement.deadline).toLocaleDateString('en-GB')} for {i.platform}. Reuse requires your review of the actual content.</p><label>Approved matching media<select className={field} value={i.asset_id??''} onChange={e=>change(i.id,{asset_id:e.target.value||null})}><option value="">Asset still required</option>{i.suggested_assets.map((a:Asset)=><option key={a.id} value={a.id}>{a.display_name} ({words(a.provenance_kind)})</option>)}</select></label></div>}
 <label className="block">Brief decision<select className={field} value={i.review} onChange={e=>change(i.id,{review:e.target.value,included:e.target.value==='rejected'?false:i.included})}><option value="pending">Needs review</option><option value="accepted">Accept brief</option><option value="rejected">Reject / exclude</option></select></label>
 <p className="text-xs break-all">Studio content: {i.id}</p>{i.role==='conversion'&&<Link to="/innovation-lab/funnel/studio" className="underline text-sm">Bind this content's tracked waitlist link in Studio</Link>}
 </div></details>)}</div>
 {error&&<p role="alert" className="my-3 text-red-800">{error}</p>}<div className="mt-4 flex flex-wrap gap-2"><button className={btn} disabled={busy||!plan.current} onClick={()=>void save(false)}>Save sequence changes</button><button className={btn} disabled={busy||!plan.current} onClick={()=>void save(true)}>Approve sequence for planning only</button><Link className={btn} to="/innovation-lab/funnel/studio">Studio / calendar / media</Link></div></article>;
}
export function NarrativePlanner(){
 const [data,setData]=useState<PlanData>({plans:[],media:[]}),[opportunities,setOpportunities]=useState<Opportunity[]>([]),[campaigns,setCampaigns]=useState<Campaign[]>([]),[source,setSource]=useState(''),[campaign,setCampaign]=useState(''),[selected,setSelected]=useState(['linkedin','instagram']),[start,setStart]=useState(new Date(Date.now()+3*86400000).toISOString().slice(0,10)),[end,setEnd]=useState(new Date(Date.now()+24*86400000).toISOString().slice(0,10)),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const load=async()=>{const [p,n,c]=await Promise.all([authenticatedApi<PlanData>('/api/growth/narrative-plans'),authenticatedApi<{opportunities:Opportunity[]}>('/api/growth/narrative-opportunities'),growthService.list('campaigns')]);setData(p);setOpportunities(n.opportunities.filter((x:Opportunity)=>x.status==='accepted'&&x.current));setCampaigns(c.filter(x=>!x.narrative_plan));};
 useEffect(()=>{void load().catch(e=>setError(e.message));},[]);
 return <section aria-label="Narrative planner" className="my-6 rounded-xl bg-white p-5 text-slate-900"><h2 className="text-xl font-bold">Narrative planner</h2><p className="my-2">Turn an accepted development into a deliberate story. Briefs and asset requests only; no generated final posts or automatic sharing.</p><div className="grid gap-3 sm:grid-cols-2"><label>Accepted development<select className={field} value={source} onChange={e=>setSource(e.target.value)}><option value="">Select accepted evidence</option>{opportunities.map(n=><option key={n.id} value={n.id}>{n.proposal.title}</option>)}</select></label><label>Campaign<select className={field} value={campaign} onChange={e=>setCampaign(e.target.value)}><option value="">Create campaign for this sequence</option>{campaigns.map(c=><option key={c.id} value={c.id}>{String(c.name)}</option>)}</select></label><label>Start date<input className={field} type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>End date<input className={field} type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label></div>
 <fieldset className="my-3"><legend>Select platforms that have a role in this story</legend><div className="flex flex-wrap gap-3">{platforms.map(p=><label key={p}><input type="checkbox" checked={selected.includes(p)} onChange={e=>setSelected(v=>e.target.checked?[...v,p]:v.filter(x=>x!==p))}/> {p}{['x','tiktok'].includes(p)?' (manual)':p==='snapchat'?' (link handoff)':''}</label>)}</div></fieldset>
 <button className={btn} disabled={busy||!source||!selected.length} onClick={async()=>{setBusy(true);setError('');try{await authenticatedApi('/api/growth/narrative-plans',{method:'POST',body:JSON.stringify({opportunity_id:source,campaign_id:campaign||null,platforms:selected,start_date:start,end_date:end})});await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Prepare narrative sequence</button><button className={`${btn} ml-2`} onClick={()=>void load().catch(e=>setError(e.message))}>Refresh accepted insights</button>
 {error&&<p role="alert" className="my-3 text-red-800">{error}</p>}{data.plans.map((p:Plan)=><PlanEditor key={`${p.id}:${p.planning_version}`} plan={p} reload={load}/>)}</section>;
}
function MediaProfile({asset,reload}:{asset:Asset;reload:()=>Promise<void>}){
 const [a,setA]=useState(asset),[confirmed,setConfirmed]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[preview,setPreview]=useState('');
 useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview);},[preview]);
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn();await reload();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <details className="rounded border p-3"><summary>{a.display_name} · {words(a.provenance_kind)} · {a.approved_for_use?'approved for use':'not approved'}</summary><div className="mt-3 space-y-2"><button className={btn} disabled={busy} onClick={()=>void run(async()=>setPreview(URL.createObjectURL(await authenticatedBlob(`/api/growth/planning-media/${a.id}/preview`))))}>Preview private source</button>{preview&&(a.mime_type?.startsWith('video/')?<video controls src={preview} className="max-h-64"/>:<img alt="Private source preview" src={preview} className="max-h-64"/>)}
 <label className="block">Actual origin<select className={field} value={a.provenance_kind} onChange={e=>setA({...a,provenance_kind:e.target.value})}>{['unknown','genuine_founder','genuine_product','designed','generated'].map(p=><option key={p}>{p}</option>)}</select></label><label className="block">Origin / creator / context<textarea className={field} value={a.provenance_notes??''} onChange={e=>setA({...a,provenance_notes:e.target.value})}/></label><label className="block">Aspect ratio<select className={field} value={a.aspect_ratio??''} onChange={e=>setA({...a,aspect_ratio:e.target.value||null})}><option value="">Unknown</option>{['9:16','4:5','1:1','16:9'].map(r=><option key={r}>{r}</option>)}</select></label><label className="block">Video duration (seconds)<input type="number" className={field} value={a.duration_seconds??''} onChange={e=>setA({...a,duration_seconds:e.target.value?Number(e.target.value):null})}/></label><div className="flex flex-wrap gap-2">{platforms.map(p=><label key={p}><input type="checkbox" checked={a.suitable_platforms.includes(p)} onChange={e=>setA({...a,suitable_platforms:e.target.checked?[...a.suitable_platforms,p]:a.suitable_platforms.filter((x:string)=>x!==p)})}/> {p}</label>)}</div><label className="block"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> I have checked the actual source and confirm this provenance and format.</label><button className={btn} disabled={busy||!confirmed} onClick={()=>void run(async()=>{await authenticatedApi(`/api/growth/planning-media/${a.id}`,{method:'PATCH',body:JSON.stringify({...a,provenance_confirmed:true})});})}>Save media provenance</button><button className={btn} disabled={busy} onClick={()=>void run(async()=>{await growthService.update('media',a.id,{approved_for_use:!a.approved_for_use});setA({...a,approved_for_use:!a.approved_for_use});})}>{a.approved_for_use?'Withdraw asset approval':'Approve asset for use'}</button><p className="text-xs">Asset approval does not create a public delivery URL or approve any post.</p>{error&&<p role="alert" className="text-red-800">{error}</p>}</div></details>;
}
export function PlanningStudio(){
 const [data,setData]=useState<Timeline>({plans:[],manual:[],ordinary:[],execution:[]}),[media,setMedia]=useState<Asset[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const load=async()=>{const [t,m]=await Promise.all([authenticatedApi<Timeline>('/api/growth/planning-timeline'),authenticatedApi<PlanData>('/api/growth/narrative-plans')]);setData(t);setMedia(m.media);};useEffect(()=>{void load().catch(e=>setError(e.message));},[]);
 const items=data.plans.flatMap((p:Plan)=>p.items.filter((i:Content)=>i.platform_brief.included).map((i:Content)=>({...i,plan:p}))).sort((a,b)=>Date.parse(a.scheduled_at)-Date.parse(b.scheduled_at));
 return <><ProductionStudio/><section className="my-6 space-y-5 rounded-xl bg-white p-5 text-slate-900"><h2 className="text-xl font-bold">Narrative calendar & media</h2><p>Intended dates are planning commitments, not automatic publishing instructions. <Link className="underline" to="/innovation-lab/funnel/intelligence">Edit your narrative sequence in Intelligence</Link>.</p>
 <div className="space-y-2">{items.map(i=><div key={i.id} className="rounded border p-3 text-sm"><strong>{new Date(i.scheduled_at).toLocaleString('en-GB')} · {i.platform} · {words(i.platform_brief.role)}</strong><p>{i.title}</p><p>Why: {i.plan.objective}</p><p>{i.plan.current?'Source current':'Source needs review'} · {i.plan.planning_approved_at?'Planning approved':'Sequence needs approval'} · Brief {i.platform_brief.review} · {i.asset_ready?'Asset ready':i.suggested_assets.length?'Review reusable asset':'Provide required asset'} · {words(i.platform_brief.execution)}</p></div>)}</div>
 <details><summary>Other calendar activities and execution schedules</summary>{data.manual.map(x=><p key={x.id}>{new Date(x.starts_at).toLocaleString('en-GB')} · {x.title} · {x.entry_type} · {x.status}</p>)}{data.ordinary.map(x=><p key={x.id}>{new Date(x.scheduled_at).toLocaleString('en-GB')} · Studio: {x.title}</p>)}{data.execution.map(x=><p key={x.id}>Provider execution intent: {x.provider} · {new Date(x.scheduled_for).toLocaleString('en-GB')} · {x.status} · Content {x.content_item_id}</p>)}</details>
 <h3 className="font-bold">Existing media library</h3><p className="text-sm">Upload genuine footage or artwork privately, record its origin, and approve it separately. Then select a suitable asset in the narrative brief. Files are reused by reference.</p><input aria-label="Upload private planning media" type="file" accept="image/jpeg,image/png,video/mp4" disabled={busy} onChange={async e=>{const f=e.target.files?.[0];if(!f)return;setBusy(true);setError('');try{const body=new FormData();body.append('file',f);await authenticatedApi('/api/growth/planning-media/upload',{method:'POST',body});await load();}catch(err){setError((err as Error).message);}finally{setBusy(false);e.target.value='';}}}/>{busy&&<p>Uploading private media…</p>}{media.map(a=><MediaProfile key={a.id} asset={a} reload={load}/>)}{error&&<p role="alert" className="text-red-800">{error}</p>}
 </section></>;
}
