import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {authenticatedApi} from '@/lib/authenticated-api';
import {growthService} from '@/services/growth/growth.service';
import type {GrowthRecord} from '@/types/growth';
type Plan={narrative:string;business_purpose:string;audience:string;timing:string;platforms:string[];notes?:string};
type Opportunity={id:string;version:number;status:string;current:boolean;source_kind:string;source_id:string;insight_id:string|null;content_item_id:string|null;deferred_until:string|null;founder_plan:Plan|null;evidence:{state:string;date:string;version:number|null;verification?:string;disclosure:string;source_path:string;work_package?:string};proposal:Plan&{title:string;evidence_summary:string;significance:string;confidence:number;reasoning:string;next_action:string;platform_roles:Record<string,string>}};
const label=(s:string)=>s.replaceAll('_',' ');
const input='mt-1 w-full rounded-lg border border-black/20 bg-white p-2 text-sm text-slate-900';
const button='rounded-lg border border-black/25 bg-white px-3 py-2 text-sm text-slate-900 disabled:opacity-40';
function OpportunityCard({item,campaigns,changed}:{item:Opportunity;campaigns:GrowthRecord[];changed:()=>Promise<void>}){
 const [plan,setPlan]=useState<Plan>(item.founder_plan??{...item.proposal,notes:''}),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[campaign,setCampaign]=useState(''),[platform,setPlatform]=useState(item.founder_plan?.platforms[0]??item.proposal.platforms[0]);
 const [until,setUntil]=useState(new Date(Date.now()+7*86400000).toISOString().slice(0,10)),[history,setHistory]=useState<Array<{decision:string;created_at:string}>|null>(null);
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn();await changed();}catch(e){setError(e instanceof Error?e.message:'This action could not be completed.');}finally{setBusy(false);}};
 const decide=(decision:string)=>run(async()=>{await authenticatedApi(`/api/growth/narrative-opportunities/${item.id}/decision`,{method:'POST',body:JSON.stringify({version:item.version,decision,...plan,disclosure_confirmed:confirmed,deferred_until:until+'T12:00:00Z'})});});
 const reviewable=['proposed','deferred'].includes(item.status);
 return <article id={`opportunity-${item.id}`} className="rounded-xl border border-black/15 bg-white p-4 text-slate-900">
  <div className="text-xs font-bold uppercase text-fuchsia-800">{item.status==='accepted'?'Founder accepted · linked Growth insight':label(item.status)}{!item.current?' · source changed — check developments again':''}</div>
  <h3 className="mt-2 font-semibold">{item.proposal.title}</h3><p className="mt-2 text-sm">{item.proposal.evidence_summary}</p>
  <dl className="mt-3 grid gap-2 text-sm"><div><dt className="font-semibold">Why Growth OS noticed this</dt><dd>{item.proposal.significance}</dd></div><div><dt className="font-semibold">Canonical evidence</dt><dd>{label(item.source_kind)} · {item.evidence.work_package??'Growth community'} · {item.evidence.state} · {new Date(item.evidence.date).toLocaleDateString('en-GB')} · source version {item.evidence.version??'not versioned'}</dd><dd className="break-all text-xs">Record: {item.source_id}</dd><dd><Link className="underline" to={item.evidence.source_path} target="_blank" rel="noopener noreferrer">Inspect canonical source in its authenticated workspace</Link></dd></div><div><dt className="font-semibold">Disclosure</dt><dd>{label(item.evidence.disclosure)}. {item.proposal.next_action}</dd></div><div><dt className="font-semibold">Confidence in the state match: {Math.round(item.proposal.confidence*100)}%</dt><dd>{item.proposal.reasoning}</dd></div></dl>
  <p className="mt-3 text-sm">Platform roles: {Object.entries(item.proposal.platform_roles).map(([p,r])=>`${p}: ${r}`).join(' ')}</p>
  {item.deferred_until&&item.status==='deferred'&&<p className="mt-2 text-sm">Deferred until {new Date(item.deferred_until).toLocaleDateString('en-GB')}. You can review it earlier.</p>}
  {reviewable&&<div className="mt-4 space-y-3"><p className="text-sm font-semibold">Review the proposed plan. Source facts remain unchanged.</p><div className="grid gap-3 sm:grid-cols-2">{Object.entries({narrative:['founder_build_journey','rd_progress','customer_insight','credibility','supplier_progress','education','waitlist_opportunity'],business_purpose:['awareness','education','credibility_nurture','conversion'],audience:['prospective_waitlist_members','community','business_partners'],timing:['after_disclosure_review','next_content_cycle','after_supporting_assets']}).map(([key,values])=><label key={key} className="text-sm">{label(key)}<select className={input} value={plan[key as keyof Plan] as string} onChange={e=>setPlan(p=>({...p,[key]:e.target.value}))}>{values.map(v=><option key={v} value={v}>{label(v)}</option>)}</select></label>)}</div>
   <fieldset><legend className="text-sm">Platforms to consider (no posting)</legend><div className="mt-2 flex flex-wrap gap-3">{['linkedin','facebook','instagram','tiktok','x','snapchat'].map(p=><label key={p} className="text-sm"><input type="checkbox" checked={plan.platforms.includes(p)} onChange={e=>setPlan(v=>({...v,platforms:e.target.checked?[...v.platforms,p]:v.platforms.filter(x=>x!==p)}))}/> {p}{p==='x'?' (manual)':p==='snapchat'?' (review/handoff constraints)':''}</label>)}</div></fieldset>
   <label className="block text-sm">Founder planning notes (not source evidence)<textarea className={input} maxLength={1500} value={plan.notes??''} onChange={e=>setPlan(p=>({...p,notes:e.target.value}))}/></label>
   <label className="flex gap-2 text-sm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I reviewed the canonical evidence and confirm this limited narrative is appropriate for external content planning. Private details and unsupported claims must stay out.</label>
   <div className="flex flex-wrap gap-2"><button className={button} disabled={busy||!item.current||!confirmed||item.evidence.disclosure==='restricted'||!plan.platforms.length} onClick={()=>void decide('accepted')}>Accept as Growth insight</button><button className={button} disabled={busy} onClick={()=>void decide('dismissed')}>Dismiss this evidence</button><button className={button} disabled={busy} onClick={()=>void decide('confidential')}>Confidential / not for content</button></div>
   <div className="flex flex-wrap items-end gap-2"><label className="text-sm">Review later<input type="date" className={input} value={until} onChange={e=>setUntil(e.target.value)}/></label><button className={button} disabled={busy||!until} onClick={()=>void decide('deferred')}>Defer opportunity</button></div>
  </div>}
  {item.status==='accepted'&&<div className="mt-4 space-y-3 border-t pt-3"><p className="text-sm">Approved purpose: {label(plan.business_purpose)} · {label(plan.narrative)}. Insight: {item.insight_id}. Acceptance is not approval to publish.</p>{item.content_item_id?<Link className="underline" to="/innovation-lab/funnel/studio">View the linked idea in Studio</Link>:<><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Planning platform<select className={input} value={platform} onChange={e=>setPlatform(e.target.value)}>{plan.platforms.map(p=><option key={p}>{p}</option>)}</select></label><label className="text-sm">Existing campaign (optional)<select className={input} value={campaign} onChange={e=>setCampaign(e.target.value)}><option value="">No campaign selected</option>{campaigns.map(c=><option key={c.id} value={c.id}>{String(c.name)}</option>)}</select></label></div><button className={button} disabled={busy||!item.current} onClick={()=>void run(async()=>{await authenticatedApi(`/api/growth/narrative-opportunities/${item.id}/content-plan`,{method:'POST',body:JSON.stringify({version:item.version,platform,campaign_id:campaign||null})});setNotice('Content idea created in Studio. No final copy or social post was generated.');})}>Create linked content idea</button></>}
   <button className={button} disabled={busy} onClick={()=>void decide('confidential')}>Mark confidential / stop further planning</button>
  </div>}
  {error&&<p role="alert" className="mt-3 text-sm text-red-800">{error}</p>}{notice&&<p role="status" className="mt-3 text-sm text-green-800">{notice}</p>}
  <button className="mt-3 text-xs underline" onClick={()=>void run(async()=>setHistory((await authenticatedApi<{history:Array<{decision:string;created_at:string}>}>(`/api/growth/narrative-opportunities/${item.id}/history`)).history))}>Show decision history</button>{history&&<ul className="mt-2 text-xs">{history.length?history.map((h,i)=><li key={i}>{label(h.decision)} · {new Date(h.created_at).toLocaleString('en-GB')}</li>):<li>No founder decision yet.</li>}</ul>}
 </article>;
}
export function NarrativeOpportunities({onChanged}:{onChanged:()=>Promise<void>}){
 const [items,setItems]=useState<Opportunity[]>([]),[campaigns,setCampaigns]=useState<GrowthRecord[]>([]),[filter,setFilter]=useState('review'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const load=async()=>{const [result,c]=await Promise.all([authenticatedApi<{opportunities:Opportunity[]}>('/api/growth/narrative-opportunities'),growthService.list('campaigns')]);setItems(result.opportunities);setCampaigns(c);};
 useEffect(()=>{void load().catch(()=>setError('Company developments could not be loaded.'));},[]);
 const shown=items.filter(i=>filter==='review'?['proposed','deferred'].includes(i.status):filter==='accepted'?i.status==='accepted':!['proposed','deferred','accepted'].includes(i.status));
 return <section aria-label="Company narrative opportunities" className="my-6 rounded-2xl border border-black/15 bg-white/80 p-5 text-slate-900"><h2 className="font-bold">Company developments → narrative opportunities</h2><p className="mt-2 text-sm">Selected canonical evidence, proposed for founder review. Support qualified waitlist interest through awareness, education, credibility or conversion; every idea does not need a waitlist CTA. No final posts are generated.</p><p className="mt-2 text-xs">This phase checks selected WP1 R&D/procurement states and permission-approved community feedback. Private financial/application records and unverified research claims are excluded.</p>
 <button className={`${button} mt-4`} disabled={busy} onClick={async()=>{setBusy(true);setError('');try{const r=await authenticatedApi<{created:number;superseded:number}>('/api/growth/narrative-opportunities/refresh',{method:'POST',body:'{}'});await load();await onChanged();setNotice(`${r.created} new opportunities; ${r.superseded} outdated opportunities superseded. Unchanged decisions are retained.`);}catch(e){setError(e instanceof Error?e.message:'The evidence check failed.');}finally{setBusy(false);}}}>Check company developments</button>
 <div className="my-4 flex flex-wrap gap-2">{[['review','New / deferred opportunities'],['accepted','Accepted insights / planning'],['history','Decision history']].map(([v,text])=><button key={v} className={button} aria-pressed={filter===v} onClick={()=>setFilter(v)}>{text}</button>)}</div>
 {error&&<p role="alert" className="text-sm text-red-800">{error}</p>}{notice&&<p role="status" className="mb-3 text-sm text-green-800">{notice}</p>}
 <div className="space-y-4">{shown.map(i=><OpportunityCard key={`${i.id}:${i.version}`} item={i} campaigns={campaigns} changed={async()=>{await load();await onChanged();}}/>)}</div>{!shown.length&&<p className="text-sm">No opportunities in this view. Check company developments to review eligible evidence; an empty result is valid.</p>}
 </section>;
}
