import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {authenticatedApi,authenticatedBlob} from '@/lib/authenticated-api';
type Candidate={approval_current?:boolean;needs_regeneration?:boolean;id:string;kind:'copy'|'asset';origin:string;created_at:string;approved_at:string|null;rejected_at:string|null;caption?:string;script?:string;guidance?:string;alt?:string;media_asset_id?:string;provider?:string};
type State={version:number;candidates:Candidate[];copy_id:string|null;asset_id:string|null};
type Item={id:string;title:string;platform:string;scheduled_at:string;production_state:State|null;platform_brief:{slot:string;role:string;review:string;included:boolean;asset_id:string|null;requirement:{kind:string;media_type:string;aspect_ratio:string;duration_seconds:number;deadline:string}}};
type Plan={id:string;name:string;current:boolean;planning_version:number;planning_approved_at:string|null;narrative_plan:{constraints:string};items:Item[]};
type Media={id:string;display_name:string;provenance_kind:string;mime_type:string};
type Data={plans:Plan[];media:Media[];generation:{notice:string}};
const btn='rounded-lg border border-slate-400 bg-white px-3 py-2 text-sm text-slate-900 disabled:opacity-40';
const field='w-full rounded border border-slate-400 bg-white p-2 text-sm text-slate-900';
const words=(s:string)=>s.replaceAll('_',' ');
export function ProductionPreview({assetId,video=false,alt='Private production draft',download=false}:{assetId:string;video?:boolean;alt?:string;download?:boolean}){
 const [url,setUrl]=useState(''),[error,setError]=useState('');
 useEffect(()=>{let disposed=false,object='';setUrl('');setError('');void authenticatedBlob(`/api/growth/planning-media/${assetId}/preview`).then(b=>{if(disposed)return;object=URL.createObjectURL(b);setUrl(object);}).catch(()=>{if(!disposed)setError('Private preview unavailable. Refresh or inspect this asset in the media library.');});return()=>{disposed=true;if(object)URL.revokeObjectURL(object);};},[assetId]);
 return <div>{error?<p role="alert" className="text-xs text-red-800">{error}</p>:url?<>{video?<video src={url} controls className="max-h-96 w-full"/>:<img src={url} alt={alt} className="w-full object-contain"/>}{download&&<a className="text-sm underline" href={url} download={`klps-${assetId}.${video?'mp4':'jpg'}`}>Download private draft</a>}</>:<p className="text-xs">Loading private preview…</p>}</div>;
}
export function ProductionGrid({items}:{items:Item[]}){
 const grid=items.filter(i=>i.platform==='instagram').sort((a,b)=>Date.parse(b.scheduled_at)-Date.parse(a.scheduled_at));
 if(!grid.length)return null;
 return <div className="my-4"><h3 className="font-bold">Instagram 3×3 production preview</h3><p className="mb-3 text-sm">Newest planned position first. Draft previews are private and are not published. Three genuine-media reservations stay protected.</p><div className="grid grid-cols-3 gap-2">{grid.map(i=>{const a=i.production_state?.candidates.find(c=>c.id===i.production_state?.asset_id&&!c.rejected_at);return <div key={i.id} className="overflow-hidden rounded border border-slate-300 bg-purple-50"><div className="aspect-[4/5] overflow-hidden">{!i.platform_brief.included?<p className="p-2 text-xs">Excluded position</p>:a?.media_asset_id?<ProductionPreview assetId={a.media_asset_id} video={i.platform_brief.requirement.media_type==='video'} alt={a.alt}/>:i.platform_brief.asset_id?<ProductionPreview assetId={i.platform_brief.asset_id} video={i.platform_brief.requirement.media_type==='video'}/>:<p className="p-3 text-xs">{i.platform_brief.requirement.kind==='genuine'?'Genuine footage reserved — Emma’s media needed':'Designed visual not prepared yet'}</p>}</div><p className="p-2 text-xs">{i.platform_brief.slot} · {words(i.platform_brief.role)}<br/>{a?.approval_current?'Asset approved':a?'Draft — review needed':'Incomplete'}</p></div>;})}</div></div>;
}
function Review({item,plan,media,reload}:{item:Item;plan:Plan;media:Media[];reload:()=>Promise<void>}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[confirmed,setConfirmed]=useState(false),[editing,setEditing]=useState(''),[caption,setCaption]=useState(''),[script,setScript]=useState(''),[asset,setAsset]=useState(''),[edited,setEdited]=useState(false),[editNotes,setEditNotes]=useState(''),[notice,setNotice]=useState('');
 const s=item.production_state??{version:0,candidates:[],copy_id:null,asset_id:null},b=item.platform_brief;
 const ready=plan.current&&Boolean(plan.planning_approved_at)&&b.included&&b.review==='accepted';
 const run=async(action:string,extra:Record<string,unknown>={})=>{setBusy(true);setError('');setNotice('');try{await authenticatedApi(`/api/growth/production/${item.id}`,{method:'POST',body:JSON.stringify({action,version:s.version,...extra})});setConfirmed(false);setEditing('');await reload();setNotice(action==='approve'?'Production approval saved. No post was approved or published.':'Production draft updated.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <details className="rounded-xl border border-slate-300 p-4"><summary className="cursor-pointer font-semibold">{item.platform} · {b.slot} · {words(b.role)} · {s.candidates.length} candidates</summary><div className="mt-3 space-y-3"><p>{item.title}</p><p className="text-sm">Evidence boundary: {plan.narrative_plan.constraints}</p>{!ready&&<p className="text-red-800">Review and approve the current sequence and brief in Intelligence before production.</p>}
 <div className="flex flex-wrap gap-2"><button className={btn} disabled={busy||!ready} onClick={()=>void run('copy')}>{s.copy_id?'Prepare another copy candidate':'Prepare platform draft'}</button>{b.requirement.kind==='designed'&&b.requirement.media_type==='image'&&<button className={btn} disabled={busy||!ready} onClick={()=>void run('visual')}>Create KLPS designed visual</button>}{b.role==='conversion'&&<button className={btn} disabled={busy||!ready} onClick={()=>void run('bind_link')}>Create / reuse content-bound waitlist link</button>}</div>
 {b.role==='conversion'&&<p className="text-xs">Create the link first, then prepare a new copy candidate to include it. Instagram uses the profile link; the guidance includes the exact tracked URL.</p>}
 {b.requirement.kind==='genuine'&&<p className="rounded bg-teal-50 p-3 text-sm">Genuine media required: {b.requirement.aspect_ratio}, approximately {b.requirement.duration_seconds??30} seconds. Needed by {new Date(b.requirement.deadline).toLocaleDateString('en-GB')}. Prepare a draft for the hook, script and shot guidance. Upload real media below; generation cannot replace this reservation.</p>}
 {b.requirement.media_type!=='none'&&<fieldset className="space-y-2 rounded border p-3"><legend>Replace / reuse existing media</legend><label className="block">Media candidate<select className={field} value={asset} onChange={e=>setAsset(e.target.value)}><option value="">Select from the existing library</option>{media.map(a=><option value={a.id} key={a.id}>{a.display_name} · {words(a.provenance_kind)}</option>)}</select></label>{b.requirement.kind==='genuine'&&<><label className="block"><input type="checkbox" checked={edited} onChange={e=>setEdited(e.target.checked)}/> This is edited genuine footage</label>{edited&&<label className="block">Edits made<textarea className={field} value={editNotes} onChange={e=>setEditNotes(e.target.value)}/></label>}</>}<button className={btn} disabled={busy||!ready||!asset||edited&&!editNotes.trim()} onClick={()=>void run('attach',{media_asset_id:asset,edited,edit_notes:editNotes})}>Use as a draft candidate</button><p className="text-xs">Record the actual provenance and matching format in the media library. Selection is not approval.</p></fieldset>}
 <label className="block rounded bg-amber-50 p-3 text-sm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> I have checked this candidate against the source evidence, disclosure limits and actual media. It makes no unsupported claims.</label>
 <div className="space-y-3">{[...s.candidates].reverse().map(c=><article key={c.id} className="space-y-2 rounded border p-3"><strong>{words(c.origin)} · {c.rejected_at?'Rejected':c.approval_current?'Approved for production':c.approved_at?'Approval needs review':'Draft'}</strong><p className="text-xs">{c.id===s.copy_id||c.id===s.asset_id?'Selected · ':''}{c.provider??'Founder supplied'} · {new Date(c.created_at).toLocaleString('en-GB')}</p>{c.kind==='copy'?editing===c.id?<><label className="block">Caption<textarea aria-label="Caption" className={field} rows={6} maxLength={3000} value={caption} onChange={e=>setCaption(e.target.value)}/></label><label className="block">Script<textarea aria-label="Script" className={field} rows={4} maxLength={8000} value={script} onChange={e=>setScript(e.target.value)}/></label><button className={btn} disabled={busy||!caption.trim()} onClick={()=>void run('edit',{candidate_id:c.id,caption,script})}>Save as new unapproved version</button></>:<><p className="whitespace-pre-wrap text-sm">{c.caption}</p>{c.script&&<pre className="whitespace-pre-wrap font-sans text-sm">{c.script}</pre>}{c.guidance&&<p className="whitespace-pre-wrap rounded bg-slate-100 p-3 text-sm">{c.guidance}</p>}</>:c.media_asset_id&&<div className="max-w-sm"><ProductionPreview assetId={c.media_asset_id} video={b.requirement.media_type==='video'} alt={c.alt} download/></div>}
 <div className="flex flex-wrap gap-2"><button className={btn} disabled={busy||!ready||Boolean(c.rejected_at)} onClick={()=>void run('select',{candidate_id:c.id})}>Select {c.kind}</button>{c.kind==='copy'&&<button className={btn} disabled={busy||!ready} onClick={()=>{setEditing(c.id);setCaption(c.caption??'');setScript(c.script??'');}}>Edit copy</button>}<button className={btn} disabled={busy||!ready||!confirmed||Boolean(c.rejected_at)} onClick={()=>void run('approve',{candidate_id:c.id,confirmed:true})}>Approve {c.kind} only</button><button className={btn} disabled={busy||!ready||Boolean(c.rejected_at)} onClick={()=>void run('reject',{candidate_id:c.id})}>Reject</button></div></article>)}</div>
 {busy&&<p role="status">Preparing private production draft…</p>}{error&&<p role="alert" className="text-red-800">{error}</p>}{notice&&<p role="status" className="text-green-800">{notice}</p>}<p className="text-xs">Copy and asset approval are separate from publishing approval. X and TikTok remain manual. Snapchat remains a reviewed web-link handoff.</p></div></details>;
}
export function ProductionStudio(){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState('');
 const load=async()=>{setData(await authenticatedApi<Data>('/api/growth/production'));};useEffect(()=>{void load().catch(e=>setError(e.message));},[]);
 return <section aria-label="Content production" className="my-6 rounded-xl bg-white p-5 text-slate-900"><h2 className="text-xl font-bold">Content production</h2><p className="my-2">Approved brief → private candidates → separate copy and asset review. Nothing here publishes.</p><p className="text-sm">{data?.generation.notice}</p><div className="my-3 flex gap-3"><Link className="underline" to="/innovation-lab/funnel/intelligence">Review narrative briefs</Link><button className={btn} onClick={()=>void load().catch(e=>setError(e.message))}>Refresh production & media</button></div>{error&&<p role="alert" className="text-red-800">{error}</p>}{data?.plans.map(p=><div key={p.id} className="my-6"><h3 className="text-lg font-bold">{p.name}</h3><ProductionGrid items={p.items}/><div className="space-y-3">{p.items.map(i=><Review key={`${i.id}:${p.planning_version}`} item={i} plan={p} media={data.media} reload={load}/>)}</div></div>)}{data&&!data.plans.length&&<p>Approve a narrative sequence in Intelligence to begin.</p>}</section>;
}
