import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import path from "node:path";
import test from "node:test";

test("Technology Blueprint extends the authenticated Data Room category and route",()=>{const room=readFileSync(path.resolve("src/pages/DataRoom.tsx"),"utf8"),app=readFileSync(path.resolve("src/App.tsx"),"utf8"),page=readFileSync(path.resolve("src/pages/DataRoomTechnologyBlueprint.tsx"),"utf8");assert.match(room,/"Technology"/);assert.match(room,/View Blueprint/);assert.match(app,/data-room\/technology\/mvp1-blueprint/);assert.match(page,/authenticatedApi\("\/api\/data-room\/documents"\)/);});
test("web and selectable-text PDF use one canonical structured publication",()=>{const page=readFileSync(path.resolve("src/pages/DataRoomTechnologyBlueprint.tsx"),"utf8"),exporter=readFileSync(path.resolve("src/features/technology-blueprint/exportBlueprintPdf.ts"),"utf8");assert.match(page,/TechnicalPublication document=\{mvp1Blueprint\}/);assert.match(page,/exportBlueprintPdf\(mvp1Blueprint\)/);assert.match(exporter,/pdf\.text/);assert.match(exporter,/Confidential — Investor Data Room/);});
test("publication keeps evidence states and rejects unsupported generated claims",()=>{const content=readFileSync(path.resolve("src/features/technology-blueprint/mvp1Blueprint.ts"),"utf8");for(const state of ["PROVEN","OBSERVED","IN DEVELOPMENT","PLANNED"])assert.match(content,new RegExp(state));for(const claim of [">20 dB","<1% BLE","95% connection","R² 0.92","R² 0.96","SoftDevice S140","Terraform","GraphQL","compression garment"])assert.doesNotMatch(content,new RegExp(claim));assert.match(content,/Arduino Nano 33 BLE Sense Rev2/);assert.match(content,/does not establish/i);});
test("publication CSS includes mobile, A4 print and hidden navigation rules",()=>{const css=readFileSync(path.resolve("src/features/technology-blueprint/blueprint.css"),"utf8");assert.match(css,/@media\(max-width:700px\)/);assert.match(css,/@media print/);assert.match(css,/\.blueprint-nav\{display:none\}/);assert.match(css,/page-break-after:always/);});
test("prototype images use canonical evidence and short-lived authorised access",()=>{const source=readFileSync(path.resolve("src/features/technology-blueprint/secureEvidenceAsset.ts"),"utf8"),content=readFileSync(path.resolve("src/features/technology-blueprint/mvp1Blueprint.ts"),"utf8");assert.match(source,/authenticatedApi/);assert.match(source,/\/api\/finance\/evidence/);assert.match(source,/action:"view"/);assert.doesNotMatch(content,/@\/assets/);});
