/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FinanceScenariosRouteImport } from './routes/finance.scenarios'
import { Route as FinanceRevenueRouteImport } from './routes/finance.revenue'
import { Route as FinanceReportsRouteImport } from './routes/finance.reports'
import { Route as FinanceProductsRouteImport } from './routes/finance.products'
import { Route as FinanceKpisRouteImport } from './routes/finance.kpis'
import { Route as FinanceHiringRouteImport } from './routes/finance.hiring'
import { Route as FinanceFundingRouteImport } from './routes/finance.funding'
import { Route as FinanceForecastsRouteImport } from './routes/finance.forecasts'
import { Route as FinanceExpensesRouteImport } from './routes/finance.expenses'
import { Route as FinanceEvidenceRouteImport } from './routes/finance.evidence'
import { Route as FinanceDocumentsRouteImport } from './routes/finance.documents'
import { Route as FinanceDashboardRouteImport } from './routes/finance.dashboard'
import { Route as FinanceCashFlowRouteImport } from './routes/finance.cash-flow'
import { Route as FinanceAssumptionsRouteImport } from './routes/finance.assumptions'
import { Route as FinanceAiInsightsRouteImport } from './routes/finance.ai-insights'

const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceScenariosRoute = FinanceScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceRevenueRoute = FinanceRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceReportsRoute = FinanceReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceProductsRoute = FinanceProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceKpisRoute = FinanceKpisRouteImport.update({
  id: '/kpis',
  path: '/kpis',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceHiringRoute = FinanceHiringRouteImport.update({
  id: '/hiring',
  path: '/hiring',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceFundingRoute = FinanceFundingRouteImport.update({
  id: '/funding',
  path: '/funding',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceForecastsRoute = FinanceForecastsRouteImport.update({
  id: '/forecasts',
  path: '/forecasts',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceExpensesRoute = FinanceExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceEvidenceRoute = FinanceEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceDocumentsRoute = FinanceDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceDashboardRoute = FinanceDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceCashFlowRoute = FinanceCashFlowRouteImport.update({
  id: '/cash-flow',
  path: '/cash-flow',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceAssumptionsRoute = FinanceAssumptionsRouteImport.update({
  id: '/assumptions',
  path: '/assumptions',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceAiInsightsRoute = FinanceAiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => FinanceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/finance': typeof FinanceRouteWithChildren
  '/finance/ai-insights': typeof FinanceAiInsightsRoute
  '/finance/assumptions': typeof FinanceAssumptionsRoute
  '/finance/cash-flow': typeof FinanceCashFlowRoute
  '/finance/dashboard': typeof FinanceDashboardRoute
  '/finance/documents': typeof FinanceDocumentsRoute
  '/finance/evidence': typeof FinanceEvidenceRoute
  '/finance/expenses': typeof FinanceExpensesRoute
  '/finance/forecasts': typeof FinanceForecastsRoute
  '/finance/funding': typeof FinanceFundingRoute
  '/finance/hiring': typeof FinanceHiringRoute
  '/finance/kpis': typeof FinanceKpisRoute
  '/finance/products': typeof FinanceProductsRoute
  '/finance/reports': typeof FinanceReportsRoute
  '/finance/revenue': typeof FinanceRevenueRoute
  '/finance/scenarios': typeof FinanceScenariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/finance': typeof FinanceRouteWithChildren
  '/finance/ai-insights': typeof FinanceAiInsightsRoute
  '/finance/assumptions': typeof FinanceAssumptionsRoute
  '/finance/cash-flow': typeof FinanceCashFlowRoute
  '/finance/dashboard': typeof FinanceDashboardRoute
  '/finance/documents': typeof FinanceDocumentsRoute
  '/finance/evidence': typeof FinanceEvidenceRoute
  '/finance/expenses': typeof FinanceExpensesRoute
  '/finance/forecasts': typeof FinanceForecastsRoute
  '/finance/funding': typeof FinanceFundingRoute
  '/finance/hiring': typeof FinanceHiringRoute
  '/finance/kpis': typeof FinanceKpisRoute
  '/finance/products': typeof FinanceProductsRoute
  '/finance/reports': typeof FinanceReportsRoute
  '/finance/revenue': typeof FinanceRevenueRoute
  '/finance/scenarios': typeof FinanceScenariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/finance': typeof FinanceRouteWithChildren
  '/finance/ai-insights': typeof FinanceAiInsightsRoute
  '/finance/assumptions': typeof FinanceAssumptionsRoute
  '/finance/cash-flow': typeof FinanceCashFlowRoute
  '/finance/dashboard': typeof FinanceDashboardRoute
  '/finance/documents': typeof FinanceDocumentsRoute
  '/finance/evidence': typeof FinanceEvidenceRoute
  '/finance/expenses': typeof FinanceExpensesRoute
  '/finance/forecasts': typeof FinanceForecastsRoute
  '/finance/funding': typeof FinanceFundingRoute
  '/finance/hiring': typeof FinanceHiringRoute
  '/finance/kpis': typeof FinanceKpisRoute
  '/finance/products': typeof FinanceProductsRoute
  '/finance/reports': typeof FinanceReportsRoute
  '/finance/revenue': typeof FinanceRevenueRoute
  '/finance/scenarios': typeof FinanceScenariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/finance'
    | '/finance/ai-insights'
    | '/finance/assumptions'
    | '/finance/cash-flow'
    | '/finance/dashboard'
    | '/finance/documents'
    | '/finance/evidence'
    | '/finance/expenses'
    | '/finance/forecasts'
    | '/finance/funding'
    | '/finance/hiring'
    | '/finance/kpis'
    | '/finance/products'
    | '/finance/reports'
    | '/finance/revenue'
    | '/finance/scenarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/finance'
    | '/finance/ai-insights'
    | '/finance/assumptions'
    | '/finance/cash-flow'
    | '/finance/dashboard'
    | '/finance/documents'
    | '/finance/evidence'
    | '/finance/expenses'
    | '/finance/forecasts'
    | '/finance/funding'
    | '/finance/hiring'
    | '/finance/kpis'
    | '/finance/products'
    | '/finance/reports'
    | '/finance/revenue'
    | '/finance/scenarios'
  id:
    | '__root__'
    | '/'
    | '/finance'
    | '/finance/ai-insights'
    | '/finance/assumptions'
    | '/finance/cash-flow'
    | '/finance/dashboard'
    | '/finance/documents'
    | '/finance/evidence'
    | '/finance/expenses'
    | '/finance/forecasts'
    | '/finance/funding'
    | '/finance/hiring'
    | '/finance/kpis'
    | '/finance/products'
    | '/finance/reports'
    | '/finance/revenue'
    | '/finance/scenarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FinanceRoute: typeof FinanceRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/scenarios': {
      id: '/finance/scenarios'
      path: '/scenarios'
      fullPath: '/finance/scenarios'
      preLoaderRoute: typeof FinanceScenariosRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/revenue': {
      id: '/finance/revenue'
      path: '/revenue'
      fullPath: '/finance/revenue'
      preLoaderRoute: typeof FinanceRevenueRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/reports': {
      id: '/finance/reports'
      path: '/reports'
      fullPath: '/finance/reports'
      preLoaderRoute: typeof FinanceReportsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/products': {
      id: '/finance/products'
      path: '/products'
      fullPath: '/finance/products'
      preLoaderRoute: typeof FinanceProductsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/kpis': {
      id: '/finance/kpis'
      path: '/kpis'
      fullPath: '/finance/kpis'
      preLoaderRoute: typeof FinanceKpisRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/hiring': {
      id: '/finance/hiring'
      path: '/hiring'
      fullPath: '/finance/hiring'
      preLoaderRoute: typeof FinanceHiringRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/funding': {
      id: '/finance/funding'
      path: '/funding'
      fullPath: '/finance/funding'
      preLoaderRoute: typeof FinanceFundingRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/forecasts': {
      id: '/finance/forecasts'
      path: '/forecasts'
      fullPath: '/finance/forecasts'
      preLoaderRoute: typeof FinanceForecastsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/expenses': {
      id: '/finance/expenses'
      path: '/expenses'
      fullPath: '/finance/expenses'
      preLoaderRoute: typeof FinanceExpensesRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/evidence': {
      id: '/finance/evidence'
      path: '/evidence'
      fullPath: '/finance/evidence'
      preLoaderRoute: typeof FinanceEvidenceRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/documents': {
      id: '/finance/documents'
      path: '/documents'
      fullPath: '/finance/documents'
      preLoaderRoute: typeof FinanceDocumentsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/dashboard': {
      id: '/finance/dashboard'
      path: '/dashboard'
      fullPath: '/finance/dashboard'
      preLoaderRoute: typeof FinanceDashboardRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/cash-flow': {
      id: '/finance/cash-flow'
      path: '/cash-flow'
      fullPath: '/finance/cash-flow'
      preLoaderRoute: typeof FinanceCashFlowRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/assumptions': {
      id: '/finance/assumptions'
      path: '/assumptions'
      fullPath: '/finance/assumptions'
      preLoaderRoute: typeof FinanceAssumptionsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/ai-insights': {
      id: '/finance/ai-insights'
      path: '/ai-insights'
      fullPath: '/finance/ai-insights'
      preLoaderRoute: typeof FinanceAiInsightsRouteImport
      parentRoute: typeof FinanceRoute
    }
  }
}

interface FinanceRouteChildren {
  FinanceAiInsightsRoute: typeof FinanceAiInsightsRoute
  FinanceAssumptionsRoute: typeof FinanceAssumptionsRoute
  FinanceCashFlowRoute: typeof FinanceCashFlowRoute
  FinanceDashboardRoute: typeof FinanceDashboardRoute
  FinanceDocumentsRoute: typeof FinanceDocumentsRoute
  FinanceEvidenceRoute: typeof FinanceEvidenceRoute
  FinanceExpensesRoute: typeof FinanceExpensesRoute
  FinanceForecastsRoute: typeof FinanceForecastsRoute
  FinanceFundingRoute: typeof FinanceFundingRoute
  FinanceHiringRoute: typeof FinanceHiringRoute
  FinanceKpisRoute: typeof FinanceKpisRoute
  FinanceProductsRoute: typeof FinanceProductsRoute
  FinanceReportsRoute: typeof FinanceReportsRoute
  FinanceRevenueRoute: typeof FinanceRevenueRoute
  FinanceScenariosRoute: typeof FinanceScenariosRoute
}

const FinanceRouteChildren: FinanceRouteChildren = {
  FinanceAiInsightsRoute: FinanceAiInsightsRoute,
  FinanceAssumptionsRoute: FinanceAssumptionsRoute,
  FinanceCashFlowRoute: FinanceCashFlowRoute,
  FinanceDashboardRoute: FinanceDashboardRoute,
  FinanceDocumentsRoute: FinanceDocumentsRoute,
  FinanceEvidenceRoute: FinanceEvidenceRoute,
  FinanceExpensesRoute: FinanceExpensesRoute,
  FinanceForecastsRoute: FinanceForecastsRoute,
  FinanceFundingRoute: FinanceFundingRoute,
  FinanceHiringRoute: FinanceHiringRoute,
  FinanceKpisRoute: FinanceKpisRoute,
  FinanceProductsRoute: FinanceProductsRoute,
  FinanceReportsRoute: FinanceReportsRoute,
  FinanceRevenueRoute: FinanceRevenueRoute,
  FinanceScenariosRoute: FinanceScenariosRoute,
}

const FinanceRouteWithChildren =
  FinanceRoute._addFileChildren(FinanceRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FinanceRoute: FinanceRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
