import {useState} from 'react';
import {useCanonicalFinance} from '@/hooks/useCanonicalFinance';
import {displayMoney,displayDate} from '@/lib/canonical-finance';
import {authenticatedApi} from '@/lib/authenticated-api';
import {PageHeader,Surface,SectionTitle} from './PageHeader';
import {CreditDecisionPanel} from './CreditDecisionPanel';
import {evidenceRepository} from '@/repositories/evidenceRepository';
export function CanonicalFinancePage({view='Dashboard'}:{view?:string}){
 const [scenario,setScenario]=useState('base'),{model,error,refresh}=useCanonicalFinance(scenario),[actionError,setActionError]=useState('');
 const evidence=async(id:string)=>{try{const result=await evidenceRepository.accessDocument(id,'view');window.open(result.signed_url,'_blank','noopener');}catch(e){setActionError(e instanceof Error?e.message:'Evidence unavailable');}};
 const exportSnapshot=()=>{if(!model)return;const url=URL.createObjectURL(new Blob([JSON.stringify(model,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='finance-canonical-snapshot.json';a.click();URL.revokeObjectURL(url);};
 return <div><PageHeader eyebrow="Finance OS · founder view" title={view} description="Evidenced cash, borrowing and obligations. Projections stay separate from account facts." actions={<><button className="rounded-lg border border-border px-3 py-2 text-sm" onClick={()=>void refresh()}>Refresh sources</button><button disabled={!model} className="rounded-lg border border-border px-3 py-2 text-sm" onClick={exportSnapshot}>Export source snapshot</button></>}/>
 {error&&<Surface><p role="alert">{error}</p><p className="mt-2 text-sm text-muted-foreground">Financial values are unavailable. No local substitute balances are shown.</p></Surface>}
 {actionError&&<p role="alert">{actionError}</p>}
 {!model&&!error&&<p role="status">Loading canonical Finance records…</p>}
 {model&&<>
 <div className="mb-5 flex flex-wrap justify-between gap-3 text-xs text-muted-foreground"><span>Cash observed: {displayDate(model.source_as_of)} · {model.actual_cash.state.replaceAll('_',' ')}</span><label>Forecast scenario <select className="ml-2 rounded border border-border bg-background p-2" value={scenario} onChange={e=>setScenario(e.target.value)}><option value="base">Base</option><option value="conservative">Conservative</option><option value="best">Best</option></select></label></div>
 {['Funding','Hiring Plan','Hiring','Risk Register'].includes(view)&&<Surface className="mb-6"><SectionTitle title={`${view} · canonical records`}/><div className="space-y-3">{(view==='Funding'?model.funding:view==='Risk Register'?model.risks:model.hires).map(row=><dl key={row.id} className="grid gap-2 rounded-lg border border-border p-3 text-sm md:grid-cols-3">{Object.entries(row).filter(([key])=>!['created_by','updated_by','scenario_id'].includes(key)).map(([key,value])=><div key={key}><dt className="text-xs text-muted-foreground">{key.replaceAll('_',' ')}</dt><dd>{value===null?'Not yet evidenced':typeof value==='object'?JSON.stringify(value):String(value)}</dd></div>)}</dl>)}{!(view==='Funding'?model.funding:view==='Risk Register'?model.risks:model.hires).length&&<p>No canonical records available.</p>}</div></Surface>}
 {view==='Assumptions'?<Surface><SectionTitle title="Canonical assumptions ledger" hint="Server records and linked evidence"/><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Assumption','Value','Status','Evidence','Edit'].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{model.assumptions.map(a=><tr key={a.id} className="border-t border-border"><td className="p-3">{a.name}</td><td className="p-3">{a.status==='needs_evidence'?'Not yet evidenced':`${a.value} ${a.unit}`}</td><td className="p-3">{a.status} · v{a.version}</td><td className="p-3">{a.evidence.length?a.evidence.map(e=><button className="mr-2 underline" key={e.evidence_id} onClick={()=>void evidence(e.evidence_id)}>{e.verification_status}</button>):'Not yet evidenced'}</td><td><button className="underline" onClick={async()=>{const value=window.prompt('New numeric value (does not verify evidence)',a.value);if(value===null)return;const reason=window.prompt('Reason for this assumption change');if(!reason)return;try{await authenticatedApi(`/api/finance/assumptions/${a.id}`,{method:'PATCH',body:JSON.stringify({value,change_reason:reason,scenario})});await refresh();}catch(e){setActionError(e instanceof Error?e.message:'Update failed');}}}>Edit value</button></td></tr>)}</tbody></table></div></Surface>:<>
 <div className="grid gap-4 md:grid-cols-3"><Metric label="CASH · Monzo / company cash" value={displayMoney(model.actual_cash.value)} note="Cash only. No borrowing capacity or planned funding." primary/><Metric label="PLANNED FUNDING" value={displayMoney(model.planned_funding)} note="Planning input only · not cash received"/><Metric label="CASH-ONLY RUNWAY" value={model.cash_only_runway_months?`${model.cash_only_runway_months} months`:model.runway_status==='no_shortfall_within_18_months'?'No shortfall within 18 months':'Not yet evidenced'} note="Excludes planned funding and unused credit"/></div>
 {model.credit.map(f=><Surface key={f.id} className="mt-6"><div className="mb-5 flex flex-wrap justify-between gap-3"><div><p className="text-xs uppercase tracking-widest text-brand-orange">Credit facility</p><h2 className="mt-1 text-xl font-semibold">{f.provider}</h2><p className="mt-1 text-sm text-muted-foreground">Revolving business credit · agreement {displayDate(f.agreement_date)}</p></div><span className="h-fit rounded-full border border-amber-500/40 bg-amber-500/10 px-3 py-2 text-xs">{f.terms?.guarantee_exists===true?'Personal guarantee evidenced':'Guarantee not yet evidenced'}</span></div>
 <div className="grid gap-3 md:grid-cols-4"><Metric label="FACILITY LIMIT" value={displayMoney(f.limit?.value)} note={f.limit?`Portal observation · ${displayDate(f.limit.as_of)}`:"Not yet evidenced"}/><Metric label="AVAILABLE CREDIT" value={displayMoney(f.available?.value)} note="Borrowing capacity · never cash"/><Metric label="UTILISED CREDIT / DEBT" value={displayMoney(f.debt?.value)} note="One liability, shown once"/><Metric label="UTILISATION" value={f.utilisation===null?'Not yet evidenced':`${f.utilisation}%`} note="Posted debt / evidenced limit"/></div>
 <div className="mt-5 grid gap-4 border-t border-border pt-5 md:grid-cols-3"><Metric label="STATEMENT BALANCE" value={displayMoney(f.statement?.closing_balance)} note={f.statement?displayDate(f.statement.statement_date):'Monthly statement required'}/><Metric label="STATEMENT MINIMUM" value={displayMoney(f.statement?.minimum_due)} note="Remaining obligation requires cleared-payment reconciliation"/><Metric label="PAYMENT DUE" value={f.statement?.due_date?displayDate(f.statement.due_date):f.portal_observation?.next_payment_display??"Not yet evidenced"} note={f.statement?.due_date?"Statement due date":"Observed portal date only · year and payment amount unknown"}/></div>
 {f.portal_observation&&<div className="mt-5 text-sm"><p>Portal period: {f.portal_observation.period_display} · year not stated.</p><p>Observed configuration: {f.portal_observation.payment_configuration_display}. Payment amount: Not yet evidenced.</p><p>Captured: {f.portal_observation.as_of} · reviewed screenshot observation.</p><p className="text-xs text-muted-foreground">{f.portal_observation.timestamp_basis}</p><button className="underline" onClick={()=>void evidence(f.portal_observation!.evidence_id)}>View private screenshot evidence</button></div>}
 <p className="mt-5 text-sm text-muted-foreground">Interest exposure and upcoming repayment pressure: not yet evidenced. Purchase and cash Business Rates are 3.43% monthly, plus the variable Bank Rate component. This is not APR or the current total applied rate.</p>
 <details className="mt-5 rounded-lg border border-border p-4 text-sm"><summary className="cursor-pointer font-medium">Contract terms, guarantee scope and source evidence</summary><p className="mt-3 text-muted-foreground">Extracted terms · version {f.term_version} · {f.review_status}. No numeric guarantee cap is stated; current debt is not a liability ceiling.</p><dl className="mt-4 space-y-4">{Object.entries(f.terms??{}).map(([key,value])=>{const source=f.term_provenance?.[key];return <div key={key}><dt className="font-medium">{key.replaceAll('_',' ')}</dt><dd className="mt-1 text-muted-foreground">{typeof value==='string'?value:JSON.stringify(value)}</dd>{source&&<button className="mt-1 text-xs underline" onClick={()=>void evidence(source.evidence_id)}>Source · page {source.page} · {source.locator} · file v{source.file_version}</button>}</div>;})}</dl></details></Surface>)}
 {!model.credit.length&&<Surface className="mt-6">No canonical credit facilities recorded.</Surface>}
 <Surface className="mt-6"><SectionTitle title="Liquidity and forecast" hint="Cash first"/><p className="text-sm">Actual cash: <strong>{displayMoney(model.actual_cash.value)}</strong>. Available credit is shown separately above.</p><p className="mt-2 text-sm">Forecast runway including planned funding: {model.forecast_runway_months?`${model.forecast_runway_months} months`:'Not yet evidenced'}</p>{model.forecast_missing.length>0?<div className="mt-4 rounded-lg border border-border p-4"><p className="font-semibold">Forecast not available</p><ul className="mt-2 list-disc pl-5 text-sm text-muted-foreground">{model.forecast_missing.map(s=><li key={s}>{s}</li>)}</ul></div>:<div className="mt-4 overflow-auto"><table className="w-full text-sm"><thead><tr><th>Month</th><th>Cash-only baseline</th><th>Including planned funding</th></tr></thead><tbody>{model.series.map(r=><tr key={r.month}><td>{r.month}</td><td>{displayMoney(r.cash)}</td><td>{displayMoney(r.forecast_cash)}</td></tr>)}</tbody></table></div>}</Surface>
 <CreditDecisionPanel facilityId={model.credit[0]?.id}/>
 </>}
 <details className="mt-6 text-xs text-muted-foreground"><summary>Calculation provenance and freshness</summary><p className="mt-2">Model {model.engine_version} · input fingerprint {model.input_fingerprint} · calculated {model.calculated_at}. Calculation time is not bank sync time.</p><p>{model.actual_cash.freshness_policy}</p></details>
 </>}
 </div>;
}
function Metric({label,value,note,primary=false}:{label:string;value:string;note:string;primary?:boolean}){return <div className={`rounded-xl border p-4 ${primary?'border-brand-orange/40 bg-brand-orange/10':'border-border bg-background/30'}`}><p className="text-[11px] font-semibold tracking-widest text-muted-foreground">{label}</p><p className="mt-3 text-xl font-semibold">{value}</p><p className="mt-2 text-xs leading-relaxed text-muted-foreground">{note}</p></div>;}
