import {useState,type FormEvent} from 'react';
import {authenticatedApi} from '@/lib/authenticated-api';
import {displayMoney} from '@/lib/canonical-finance';
import type {Projection} from '@/types/finance-canonical';
import {Surface,SectionTitle} from './PageHeader';
const input='mt-1 w-full rounded-lg border border-border bg-background px-3 py-2 text-sm';
export function CreditDecisionPanel({facilityId}:{facilityId?:string}){
 const [values,setValues]=useState<Record<string,string>>({mode:'full',proposed_kind:'purchase'}),[checked,setChecked]=useState(false),[result,setResult]=useState<Projection|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[saved,setSaved]=useState(false);
 const set=(key:string,value:string)=>{setValues(v=>({...v,[key]:value}));setResult(null);setSaved(false);};
 const submit=async(e:FormEvent,save=false)=>{e.preventDefault();setBusy(true);setError('');try{const fields:Record<string,unknown>=Object.fromEntries(Object.entries(values).filter(([,v])=>v!==''));for(const key of ['due_days','horizon_months','payoff_months'])if(fields[key]!==undefined)fields[key]=Number(fields[key]);if(fields.purchase_interest_free!==undefined)fields.purchase_interest_free=fields.purchase_interest_free==='yes';Object.assign(fields,{assumptions_acknowledged:checked,no_other_debt_or_arrears:checked,no_further_spending:checked});const r=await authenticatedApi<{projection:Projection}>('/api/finance/credit-scenarios',{method:'POST',body:JSON.stringify({inputs:fields,save,facility_id:facilityId})});setResult(r.projection);setSaved(save&&r.projection.status!=='blocked');}catch(e){setError(e instanceof Error?e.message:'Projection unavailable');}finally{setBusy(false);}};
 return <Surface className="mt-6"><SectionTitle title="What happens if we spend?" hint="Decision support · estimates only"/><p className="mb-5 text-sm text-muted-foreground">Supply explicit planning assumptions. The agreement alone does not establish opening balances, current applied rates or billing dates. These inputs do not change your account or Direct Debit.</p>
 <form onSubmit={submit}><div className="grid gap-4 md:grid-cols-3">
 <label className="text-sm">Repayment option<select className={input} value={values.mode} onChange={e=>set('mode',e.target.value)}><option value="full">Pay statement in full</option><option value="minimum">Contractual minimum</option><option value="fixed">Fixed payment</option><option value="period">Repayment period</option></select></label>
 <label className="text-sm">Proposed transaction<select className={input} value={values.proposed_kind} onChange={e=>set('proposed_kind',e.target.value)}><option value="purchase">Card purchase</option><option value="cash_withdrawal">Cash withdrawal</option></select></label>
 {([['proposed_amount','Proposed spend (£)','text'],['opening_purchase','Opening purchase debt (£)','text'],['opening_cash','Opening cash withdrawal debt (£)','text'],['start_date','Simulation start','date'],['proposed_date','Proposed debit date','date'],['first_statement_date','First statement date','date'],['horizon_months','Projection horizon (months, default 60)','number'],['due_days','Clearing days after statement (calendar)','number'],['purchase_daily_rate','Purchase daily rate (decimal, not APR)','text'],['cash_daily_rate','Cash daily rate (decimal, not APR)','text'],['fixed_payment','Fixed payment (£)','text'],['payoff_months','Repayment period (months)','number'],['cash_on_hand','Cash for runway (£, optional)','text'],['monthly_cash_receipts','Monthly cash receipts (£, optional)','text'],['monthly_direct_cash_costs','Direct cash costs excluding card (£, optional)','text']] as const).filter(([key])=>key!=='fixed_payment'||values.mode==='fixed').filter(([key])=>key!=='payoff_months'||values.mode==='period').map(([key,label,type])=><label key={key} className="text-sm">{label}<input className={input} type={type} value={values[key]??''} onChange={e=>set(key,e.target.value)}/></label>)}
 <label className="text-sm">Prior purchase interest-free status<select className={input} value={values.purchase_interest_free??''} onChange={e=>set('purchase_interest_free',e.target.value)}><option value="">Not yet evidenced</option><option value="yes">Eligible (explicit assumption)</option><option value="no">Ineligible (explicit assumption)</option></select></label>
 <label className="text-sm">Equal-rate allocation assumption<select className={input} value={values.equal_rate_allocation??''} onChange={e=>set('equal_rate_allocation',e.target.value)}><option value="">Select explicitly</option><option value="purchase_first">Purchases first</option><option value="cash_first">Cash withdrawals first</option></select></label>
 <label className="text-sm md:col-span-3">Rate source / explanation of assumptions<input className={input} value={values.rate_assumption_source??''} onChange={e=>set('rate_assumption_source',e.target.value)}/></label>
 </div><label className="my-5 flex items-start gap-3 text-sm"><input type="checkbox" checked={checked} onChange={e=>{setChecked(e.target.checked);setResult(null);}}/><span>I confirm these are explicit estimates: all opening debt is entered, there are no other fees, arrears or arrangements, and there is no further spending beyond the proposed transaction. Dates, daily rates and allocation are assumptions; they are not verified lender calculations.</span></label>
 <div className="flex gap-3"><button disabled={busy} className="rounded-lg bg-brand-orange px-5 py-2 text-sm font-semibold text-black">{busy?'Calculating…':'Compare repayment scenario'}</button><button type="button" disabled={busy||!result||result.status==='blocked'} onClick={e=>void submit(e,true)} className="rounded-lg border border-border px-4 py-2 text-sm disabled:opacity-40">Save estimate only</button></div></form>
 {error&&<p role="alert" className="mt-4 text-red-500">{error}</p>}{saved&&<p role="status" className="mt-4">Estimate saved. No financial instruction created.</p>}
 {result?.status==='blocked'&&<div className="mt-5 rounded-lg border border-amber-500/40 p-4"><p className="font-semibold">Projection blocked: required assumptions are missing</p><ul className="mt-2 list-disc pl-5 text-sm">{result.missing.map(x=><li key={x}>{x}</li>)}</ul></div>}
 {result&&result.status!=='blocked'&&<div className="mt-6"><p className="text-sm font-semibold">ESTIMATE · {result.engine_version}</p><div className="my-4 grid gap-3 md:grid-cols-4">{[['Interest',displayMoney(result.estimated_interest)],['Total paid in horizon',displayMoney(result.estimated_total_repayment)],['Payoff',result.payoff_date??'Not repaid within horizon'],['Interest versus full repayment',displayMoney(result.difference_vs_full?.interest)]].map(([label,value])=><div key={label} className="rounded-lg border border-border p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-semibold">{value}</p></div>)}</div>
 <p className="text-sm">Cash shortfall: {result.cash_runway_status==='not_available'?'Not available — cash assumptions missing':result.cash_shortfall_date??'No shortfall within horizon'} · Without proposed spend: {result.purchase_impact?.cash_shortfall_without_purchase??'Not established / none within horizon'}</p>
 <div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Clearing date','Minimum','Repayment','Interest','Debt remaining','Cash remaining','Payment shortfall'].map(h=><th className="p-2" key={h}>{h}</th>)}</tr></thead><tbody>{result.schedule?.map(r=><tr className="border-t border-border" key={r.date}><td className="p-2">{r.date}</td>{[r.required_minimum,r.payment,r.interest,r.closing_debt,r.cash_remaining,r.shortfall].map((v,n)=><td className="p-2" key={n}>{displayMoney(v)}</td>)}</tr>)}</tbody></table></div><details className="mt-4 text-sm"><summary>Source assumptions and limitations</summary><pre className="mt-3 overflow-auto whitespace-pre-wrap">{JSON.stringify(result.assumptions,null,2)}</pre><ul className="list-disc pl-5">{result.limitations?.map(x=><li key={x}>{x}</li>)}</ul></details></div>}
 </Surface>;
}
