import type { FinancialAssumption } from "@/types/finance";

const audit = (date: string, by = "Emma / Founder") => ({
  created_at: date,
  updated_at: date,
  created_by: by,
  updated_by: by,
  version: 1,
  change_reason: "Initial finance model seed",
});

export const seedAssumptions: FinancialAssumption[] = [
  {
    id: "asp",
    category: "Pricing",
    name: "Average Selling Price",
    value: 249,
    unit: "GBP",
    confidence: 82,
    confidenceLevel: "Research",
    source: "Pricing study Q1",
    owner: "Founder",
    status: "Active",
    evidenceIds: ["ev-1"],
    notes: "Validated against waitlist pricing study and competitor positioning.",
    linkedMetrics: ["Hardware Revenue", "Gross Margin", "Cash Flow"],
    history: [{ version: 0, value: 229, at: "2026-03-01", by: "Founder", reason: "Early prototype pricing" }],
    ...audit("2026-06-14"),
  },
  {
    id: "sub_price",
    category: "Pricing",
    name: "Subscription Price (monthly)",
    value: 12,
    unit: "GBP/mo",
    confidence: 74,
    confidenceLevel: "Survey",
    source: "Survey n=412",
    owner: "Founder",
    status: "Active",
    evidenceIds: ["ev-2"],
    notes: "Monthly intelligence subscription placeholder until pilot retention data lands.",
    linkedMetrics: ["MRR", "ARR", "LTV"],
    history: [{ version: 0, value: 9, at: "2026-01-15", by: "Founder", reason: "Original beta price" }],
    ...audit("2026-05-02"),
  },
  {
    id: "sub_uptake",
    category: "Pricing",
    name: "Subscription Uptake",
    value: 0.42,
    unit: "%",
    confidence: 68,
    confidenceLevel: "Pilot Data",
    source: "Beta cohort",
    owner: "Growth Lead",
    status: "Needs Review",
    evidenceIds: [],
    notes: "Needs revalidation after the next cohort completes onboarding.",
    linkedMetrics: ["Subscription Revenue", "MRR", "LTV"],
    history: [],
    ...audit("2026-05-18", "Growth Lead"),
  },
  {
    id: "mfg_cost",
    category: "Manufacturing",
    name: "Unit Manufacturing Cost",
    value: 68,
    unit: "GBP",
    confidence: 88,
    confidenceLevel: "Supplier Quote",
    source: "Supplier quote - Shenzhen A",
    owner: "Operations",
    status: "Active",
    evidenceIds: ["ev-3"],
    notes: "Includes sensor mesh assembly but excludes packaging and fulfilment.",
    linkedMetrics: ["COGS", "Gross Margin", "Cash Flow"],
    history: [],
    ...audit("2026-06-01", "Operations"),
  },
  {
    id: "packaging",
    category: "Manufacturing",
    name: "Packaging",
    value: 6.5,
    unit: "GBP",
    confidence: 90,
    confidenceLevel: "Supplier Quote",
    source: "Vendor invoice",
    owner: "Operations",
    status: "Verified",
    evidenceIds: ["ev-7"],
    notes: "Eco-mailer and insert placeholder cost.",
    linkedMetrics: ["COGS", "Gross Margin"],
    history: [],
    ...audit("2026-04-11", "Operations"),
  },
  {
    id: "shipping",
    category: "Manufacturing",
    name: "Shipping / Fulfilment",
    value: 9,
    unit: "GBP",
    confidence: 80,
    confidenceLevel: "Contract",
    source: "3PL contract",
    owner: "Operations",
    status: "Active",
    evidenceIds: ["ev-8"],
    notes: "UK blended fulfilment assumption.",
    linkedMetrics: ["COGS", "Gross Margin"],
    history: [],
    ...audit("2026-04-11", "Operations"),
  },
  {
    id: "waitlist",
    category: "Marketing",
    name: "Waitlist Size",
    value: 18400,
    unit: "signups",
    confidence: 95,
    confidenceLevel: "Actual",
    source: "Segment export",
    owner: "Growth Lead",
    status: "Verified",
    evidenceIds: ["ev-9"],
    notes: "Founder and invited-guest dashboards should treat this as read-only until CRM sync.",
    linkedMetrics: ["Units", "Revenue Forecast", "Cash Flow"],
    history: [],
    ...audit("2026-07-01", "Growth Lead"),
  },
  {
    id: "conv",
    category: "Marketing",
    name: "Waitlist to Buyer Conversion",
    value: 0.18,
    unit: "%",
    confidence: 62,
    confidenceLevel: "Estimated",
    source: "Comparable launches",
    owner: "Growth Lead",
    status: "Needs Review",
    evidenceIds: ["ev-10"],
    notes: "Comparable wearable launches weighted down for pre-revenue uncertainty.",
    linkedMetrics: ["Units", "Hardware Revenue", "CAC Payback"],
    history: [],
    ...audit("2026-06-20", "Growth Lead"),
  },
  {
    id: "cac",
    category: "Marketing",
    name: "Blended CAC",
    value: 41,
    unit: "GBP",
    confidence: 71,
    confidenceLevel: "Historical",
    source: "Meta + Google Q2",
    owner: "Growth Lead",
    status: "Active",
    evidenceIds: ["ev-5"],
    notes: "Includes paid social, search, referrals and launch partnerships.",
    linkedMetrics: ["Marketing Spend", "LTV / CAC", "Burn"],
    history: [],
    ...audit("2026-06-30", "Growth Lead"),
  },
  {
    id: "growth_mom",
    category: "Growth",
    name: "Monthly Growth Rate",
    value: 0.09,
    unit: "%",
    confidence: 66,
    confidenceLevel: "Estimated",
    source: "Base case model",
    owner: "Founder",
    status: "Active",
    evidenceIds: [],
    notes: "Scenario multiplier changes this assumption without altering source data.",
    linkedMetrics: ["Revenue Forecast", "Cash Flow", "Runway"],
    history: [],
    ...audit("2026-06-01"),
  },
  {
    id: "ent_rev",
    category: "Growth",
    name: "Enterprise Contract (annual)",
    value: 42000,
    unit: "GBP",
    confidence: 55,
    confidenceLevel: "Expert Opinion",
    source: "2 signed LOIs",
    owner: "Founder",
    status: "Needs Review",
    evidenceIds: ["ev-4"],
    notes: "Placeholder for workplace wellbeing and research-platform partnerships.",
    linkedMetrics: ["Enterprise Revenue", "ARR", "Forecast Risk"],
    history: [],
    ...audit("2026-05-25"),
  },
  {
    id: "ent_count",
    category: "Growth",
    name: "Enterprise Contracts / yr",
    value: 6,
    unit: "count",
    confidence: 50,
    confidenceLevel: "Estimated",
    source: "Sales pipeline",
    owner: "Founder",
    status: "Needs Review",
    evidenceIds: [],
    notes: "Pipeline count should be linked to CRM once PostgreSQL backend is live.",
    linkedMetrics: ["Enterprise Revenue", "ARR"],
    history: [],
    ...audit("2026-06-10"),
  },
  {
    id: "opening_cash",
    category: "Finance",
    name: "Opening Cash",
    value: 1250000,
    unit: "GBP",
    confidence: 100,
    confidenceLevel: "Verified",
    source: "Bank statement Jul 2026",
    owner: "Finance",
    status: "Verified",
    evidenceIds: ["ev-6"],
    notes: "Starting point for the Finance OS cash-flow ledger.",
    linkedMetrics: ["Cash on Hand", "Runway", "Cash Flow"],
    history: [],
    ...audit("2026-07-01", "Finance"),
  },
  {
    id: "tax_rate",
    category: "Finance",
    name: "Effective Tax Rate",
    value: 0.19,
    unit: "%",
    confidence: 95,
    confidenceLevel: "Actual",
    source: "HMRC",
    owner: "Finance",
    status: "Active",
    evidenceIds: [],
    notes: "UK corporation tax placeholder.",
    linkedMetrics: ["Net Margin", "Reports"],
    history: [],
    ...audit("2026-01-01", "Finance"),
  },
  {
    id: "hire_ramp",
    category: "Hiring",
    name: "Employer NI + Benefits",
    value: 0.18,
    unit: "%",
    confidence: 98,
    confidenceLevel: "Actual",
    source: "HMRC + payroll",
    owner: "Finance",
    status: "Active",
    evidenceIds: [],
    notes: "Loaded cost assumption for every hire.",
    linkedMetrics: ["Payroll", "Burn", "Runway"],
    history: [],
    ...audit("2026-04-06", "Finance"),
  },
];
