import type { AssumptionCategory, FinancialAssumption } from "@/types/finance";

const unknownAssumption = (
  id: string,
  category: AssumptionCategory,
  name: string,
  unit: string,
  linkedMetrics: string[],
): FinancialAssumption => ({
  id,
  category,
  name,
  value: 0,
  unit,
  confidence: 0,
  confidenceLevel: "Unknown",
  source: "",
  owner: category === "Pricing" || category === "Growth" ? "Founder" : "",
  status: "Unknown",
  evidenceIds: [],
  notes: "Not yet evidenced.",
  linkedMetrics,
  history: [],
  created_at: "",
  updated_at: "",
  created_by: "",
  updated_by: "",
  version: 1,
  change_reason: "Reset to truthful V1 baseline; evidence required before activation.",
});

export const seedAssumptions: FinancialAssumption[] = [
  unknownAssumption("asp", "Pricing", "Average Selling Price", "GBP", ["Hardware Revenue", "Gross Margin", "Cash Flow"]),
  unknownAssumption("sub_price", "Pricing", "Subscription Price (monthly)", "GBP/mo", ["MRR", "ARR", "LTV"]),
  unknownAssumption("sub_uptake", "Pricing", "Subscription Uptake", "%", ["Subscription Revenue", "MRR", "LTV"]),
  unknownAssumption("mfg_cost", "Manufacturing", "Unit Manufacturing Cost", "GBP", ["COGS", "Gross Margin", "Cash Flow"]),
  unknownAssumption("packaging", "Manufacturing", "Packaging", "GBP", ["COGS", "Gross Margin"]),
  unknownAssumption("shipping", "Manufacturing", "Shipping / Fulfilment", "GBP", ["COGS", "Gross Margin"]),
  unknownAssumption("waitlist", "Marketing", "Waitlist Size", "signups", ["Units", "Revenue Forecast", "Cash Flow"]),
  unknownAssumption("conv", "Marketing", "Waitlist to Buyer Conversion", "%", ["Units", "Hardware Revenue", "CAC Payback"]),
  unknownAssumption("cac", "Marketing", "Blended CAC", "GBP", ["Marketing Spend", "LTV / CAC", "Burn"]),
  unknownAssumption("growth_mom", "Growth", "Monthly Growth Rate", "%", ["Revenue Forecast", "Cash Flow", "Runway"]),
  unknownAssumption("ent_rev", "Growth", "Enterprise Contract (annual)", "GBP", ["Enterprise Revenue", "ARR", "Forecast Risk"]),
  unknownAssumption("ent_count", "Growth", "Enterprise Contracts / yr", "count", ["Enterprise Revenue", "ARR"]),
  unknownAssumption("opening_cash", "Finance", "Opening Cash", "GBP", ["Cash on Hand", "Runway", "Cash Flow"]),
  unknownAssumption("tax_rate", "Finance", "Effective Tax Rate", "%", ["Net Margin", "Reports"]),
  unknownAssumption("hire_ramp", "Hiring", "Employer NI + Benefits", "%", ["Payroll", "Burn", "Runway"]),
];
