import type { CompanyRecord } from "@/types/company";

export const companyDefaults: CompanyRecord = {
  companyName: "KLPS Ltd",
  legalName: "KIDS, LADIES & PARENTS, SPECIALISTS LTD",
  tradingName: "KLPS",
  companyNumber: "16436591",
  companyType: "UK Private Limited Company",
  companyStatus: "Active",
  operatingStatus: "Pre-revenue",
  industry: ["Deep Technology", "Smart Textiles", "FemTech"],
  country: "United Kingdom",
  incorporationDate: "2025-05-08",
  registeredOffice: {
    addressLine1: "Unit 3a Imex Industrial Estate",
    addressLine2: "Western House",
    addressLine3: "Western Road",
    city: "Hockley",
    region: "Birmingham, West Midlands",
    postcode: "B18 7QD",
    country: "United Kingdom",
  },
  baseCurrency: "GBP",
  financialYearEnd: "31 May",
  firstAccountsPeriodEnd: "2026-05-31",
  firstAccountsFilingDeadline: "2027-02-08",
  founder: "Emma Mendez",
  sicCodes: ["13990", "62012", "72190", "74100"],
  vatStatus: "Approved",
  vatRegistrationNumber: "522998359",
  vatEffectiveDate: "2025-05-08",
  vatScheme: "Annual Accounting Scheme",
  vatAccountingPeriodStart: "2025-05-08",
  vatAccountingPeriodEnd: "2026-04-30",
  vatLetterIssueDate: "2026-07-11",
  vatEvidenceIds: [],
  vatEvidenceSource: "HMRC VAT Registration Approved letter",
  vatLastReviewed: null,
  accountingMethod: null,
  externalAccountantStatus: "Appointed",
  accountingSoftware: "FreeAgent",
  accountingSoftwareStatus: "Planned Integration",
  corporationTaxStatus: "Unknown",
  icoStatus: "Not Started",
  icoRegistrationNumber: null,
  seisStatus: "Preparing",
  seisAdvanceAssuranceStatus: "Not Submitted",
  seisTargetSubmissionPeriod: "July 2026",
  seisDecisionDate: null,
  seisReferenceNumber: null,
  seisEvidenceIds: [],
  seisOwner: "Emma Mendez",
  seisSource: "Founder action plan",
  seisNotes: "SEIS advance assurance application planned for submission this week",
  bankStatus: "Application Pending",
  operatingBankName: "Starling Business",
  businessBankAccount: null,
  bankBalance: null,
  trl: 3,
  crl: null,
  currentRaiseAmount: 250000,
  fundraisingScheme: "SEIS",
  fundraisingStatus: "Preparing HMRC Advance Assurance",
  legalPartner: "FounderCatalyst",
  legalPartnerStatus: "Introductory call scheduled",
  currentFundingSources: ["Founder investment", "Grant funding", "Equity investment"],
  futureRevenueSources: ["Smart textile products", "Software subscriptions", "Enterprise partnerships", "Technology licensing"],
  milestones: [
    { id: "incorporated", title: "Company incorporated", status: "Completed" },
    { id: "vat-registered", title: "VAT registration complete", status: "Completed" },
    { id: "working-mvp", title: "Working MVP completed", status: "Completed" },
    { id: "customer-discovery", title: "Customer discovery completed", status: "Completed" },
    { id: "accelerators", title: "Three accelerator programmes completed", status: "Completed" },
    { id: "uom-collaboration", title: "University of Manchester collaboration", status: "In Progress" },
    { id: "seis-assurance", title: "SEIS Advance Assurance", status: "In Progress" },
    { id: "seis-raise", title: "£250k SEIS raise", status: "In Progress" },
  ],
  dataStatus: "Verified",
  evidenceIds: [],
  confidence: 100,
  source: "Founder-provided verified company facts",
  owner: "Emma Mendez",
  lastReviewed: null,
  notes: "VAT registration approved by HMRC. SEIS advance assurance preparation is in progress and has not yet been submitted.",
  createdAt: null,
  updatedAt: null,
  createdBy: null,
  updatedBy: null,
  version: 1,
  changeReason: "Initial verified Company V1 record",
};
