/** Network DTO. Field names and nullability match finance_os.expenses. */
export interface ExpenseDto {
  id: string;
  import_key: string;
  name: string;
  supplier_name: string | null;
  category: string;
  cost_type: string;
  frequency: string | null;
  transaction_date: string | null;
  service_period_start: string | null;
  service_period_end: string | null;
  currency: string;
  net_amount: number | null;
  credit_adjustment: number | null;
  vat_amount: number | null;
  vat_rate: number | null;
  gross_amount: number | null;
  supplier_cost_amount: number | null;
  supplier_cost_basis: string | null;
  recurring_run_rate_net: number | null;
  recurring_run_rate_vat_rate: number | null;
  klps_allocation_amount: number | null;
  klps_allocation_percentage: number | null;
  current_status: string;
  paid_by: string | null;
  payment_channel: string | null;
  reimbursement_status: string | null;
  company_cash_outflow: boolean | null;
  business_expense_status: string | null;
  evidence_status: string;
  evidence_reference: string | null;
  evidence_id: string | null;
  notes: string | null;
  metadata: Record<string, unknown>;
  created_at: string;
  updated_at: string;
  created_by: string | null;
  updated_by: string | null;
  version: number;
  change_reason: string;
}

export interface Expense {
  id: string;
  importKey: string;
  name: string;
  supplierName: string | null;
  category: string;
  costType: string;
  frequency: string | null;
  transactionDate: string | null;
  servicePeriodStart: string | null;
  servicePeriodEnd: string | null;
  currency: string;
  netAmount: number | null;
  creditAdjustment: number | null;
  vatAmount: number | null;
  vatRate: number | null;
  grossAmount: number | null;
  supplierCostAmount: number | null;
  supplierCostBasis: string | null;
  recurringRunRateNet: number | null;
  recurringRunRateVatRate: number | null;
  klpsAllocationAmount: number | null;
  klpsAllocationPercentage: number | null;
  currentStatus: string;
  paidBy: string | null;
  paymentChannel: string | null;
  reimbursementStatus: string | null;
  companyCashOutflow: boolean | null;
  businessExpenseStatus: string | null;
  evidenceStatus: string;
  evidenceReference: string | null;
  evidenceId: string | null;
  notes: string | null;
  metadata: Record<string, unknown>;
  updatedAt: string;
  version: number;
  changeReason: string;
}
