import { useCallback,useEffect,useMemo,useState,type FormEvent } from "react";
import { AlertTriangle,FileSpreadsheet,RefreshCw,ShieldCheck,Upload } from "lucide-react";
import { PageHeader,SectionTitle,Surface } from "@/components/finance/PageHeader";
import { bankImportRepository } from "@/repositories/bankImportRepository";
import type { BankImportRun,BankTransaction,MonzoCsvImportResult,ProviderEnvironment } from "@/types/banking";

const input="mt-1 w-full rounded-lg border border-border bg-background px-3 py-2 text-sm";
const date=(value:string|null)=>value?new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"short",year:"numeric"}).format(new Date(`${value.slice(0,10)}T00:00:00Z`)):"—";
const money=(value:string,currency:string)=>new Intl.NumberFormat("en-GB",{style:"currency",currency}).format(Number(value));

export default function BankImportsPage(){
  const[imports,setImports]=useState<BankImportRun[]>([]),[transactions,setTransactions]=useState<BankTransaction[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
  const[file,setFile]=useState<File|null>(null),[environment,setEnvironment]=useState<ProviderEnvironment|"">(""),[accountLabel,setAccountLabel]=useState("Monzo Business"),[busy,setBusy]=useState(false),[result,setResult]=useState<MonzoCsvImportResult|null>(null);
  const load=useCallback(async()=>{setLoading(true);try{const[runs,rows]=await Promise.all([bankImportRepository.imports(),bankImportRepository.transactions()]);setImports(runs);setTransactions(rows);setError("");}catch(reason){setError(reason instanceof Error?reason.message:"Bank imports are unavailable");}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);
  const unmatched=useMemo(()=>transactions.filter(item=>item.reconciliation_status==="unmatched").length,[transactions]);
  const submit=async(event:FormEvent)=>{event.preventDefault();if(!file||!environment||!accountLabel.trim())return;setBusy(true);setError("");setResult(null);try{const imported=await bankImportRepository.importMonzoCsv(file,environment,accountLabel.trim());setResult(imported);await load();}catch(reason){setError(reason instanceof Error?reason.message:"Monzo CSV import failed");}finally{setBusy(false);}};
  return <div><PageHeader eyebrow="Read-only banking foundation" title="Bank Imports" description="Stage Monzo statements with explicit provenance and idempotency. Imports do not create expenses, change VAT records, or connect to a bank."/>
    <div className="mb-5 grid gap-4 md:grid-cols-3"><Stat label="Imported statement runs" value={String(imports.length)}/><Stat label="Staged transactions" value={String(transactions.length)}/><Stat label="Awaiting reconciliation" value={String(unmatched)}/></div>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,0.9fr)_minmax(0,1.5fr)]"><Surface><SectionTitle title="Import a Monzo CSV" hint="Founder/admin only"/><form onSubmit={submit} className="space-y-4">
      <div className="rounded-xl border border-brand-sage/30 bg-brand-sage/10 p-3 text-sm"><div className="flex items-center gap-2 font-semibold"><ShieldCheck className="h-4 w-4"/>Staging only</div><p className="mt-1 text-muted-foreground">No bank credentials are used. No expense, VAT treatment, evidence link, payment or balance is changed.</p></div>
      <label className="block text-sm font-medium">Monzo statement CSV<input required type="file" accept=".csv,text/csv" className={input} onChange={event=>setFile(event.target.files?.[0]??null)}/></label>
      <label className="block text-sm font-medium">Account label<input required className={input} maxLength={120} value={accountLabel} onChange={event=>setAccountLabel(event.target.value)}/></label>
      <label className="block text-sm font-medium">Provider environment<select required className={input} value={environment} onChange={event=>setEnvironment(event.target.value as ProviderEnvironment|"")}><option value="">Select explicitly</option><option value="sandbox">Sandbox — synthetic/test statement</option><option value="production">Production — real Monzo statement</option></select></label>
      {environment==="production"&&<div className="flex gap-2 rounded-xl border border-amber-300 bg-amber-50 p-3 text-sm text-amber-950"><AlertTriangle className="mt-0.5 h-4 w-4 shrink-0"/><span>This records real-statement provenance only. It does not connect to Monzo or contact a production banking API.</span></div>}
      <button disabled={busy||!file||!environment||!accountLabel.trim()} className="inline-flex w-full items-center justify-center gap-2 rounded-lg bg-brand-orange px-4 py-2.5 text-sm font-semibold text-primary-foreground disabled:opacity-50"><Upload className="h-4 w-4"/>{busy?"Importing…":"Import statement"}</button>
      {result&&<div role="status" className="rounded-xl border border-border p-3 text-sm"><div className="font-semibold">{result.duplicate_file?"Statement already imported":"Statement staged successfully"}</div><p className="mt-1 text-muted-foreground">{result.sync_run.inserted_count} inserted · {result.sync_run.updated_count} refreshed · {result.sync_run.skipped_count} skipped</p></div>}
    </form></Surface>
    <Surface><div className="flex items-start justify-between gap-3"><SectionTitle title="Staged transactions" hint="No automatic accounting writes"/><button type="button" onClick={()=>void load()} disabled={loading} className="rounded-lg border border-border p-2 text-muted-foreground" aria-label="Refresh bank imports"><RefreshCw className={`h-4 w-4 ${loading?"animate-spin":""}`}/></button></div>
      {error&&<div role="alert" className="mb-4 text-sm text-brand-coral">{error}</div>}
      <div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="border-b border-border text-xs uppercase tracking-wider text-muted-foreground"><tr><th className="pb-3">Date</th><th className="pb-3">Counterparty</th><th className="pb-3">Source</th><th className="pb-3">Status</th><th className="pb-3 text-right">Amount</th></tr></thead><tbody>{transactions.map(item=><tr key={item.id} className="border-b border-border/60"><td className="py-3">{date(item.booking_date)}</td><td className="py-3"><div className="font-medium">{item.merchant_name??item.counterparty_name??item.description??"Unlabelled transaction"}</div>{item.reference&&<div className="max-w-xs truncate text-xs text-muted-foreground">{item.reference}</div>}</td><td className="py-3 text-xs text-muted-foreground">{item.provider} · {item.provider_environment}</td><td className="py-3"><span className="rounded-full border border-border px-2 py-1 text-xs">{item.reconciliation_status}</span></td><td className={`py-3 text-right font-semibold ${item.direction==="credit"?"text-green-700":""}`}>{money(item.amount,item.currency)}</td></tr>)}</tbody></table></div>
      {!loading&&!transactions.length&&!error&&<div className="py-12 text-center"><FileSpreadsheet className="mx-auto h-8 w-8 text-muted-foreground"/><p className="mt-3 text-sm text-muted-foreground">No bank transactions have been staged.</p></div>}
    </Surface></div>
    <Surface className="mt-5"><SectionTitle title="Import history"/><div className="space-y-2">{imports.map(run=><div key={run.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-border p-3 text-sm"><div><div className="font-medium">{run.source_filename??"Monzo CSV"}</div><div className="text-xs text-muted-foreground">{run.account_label??"Account"} · {run.provider_environment} · {date(run.started_at)}</div></div><div className="text-right"><div>{run.inserted_count} inserted · {run.updated_count} refreshed</div><div className="text-xs text-muted-foreground">{run.status}</div></div></div>)}{!imports.length&&!loading&&<p className="text-sm text-muted-foreground">No import runs recorded.</p>}</div></Surface>
  </div>;
}
function Stat({label,value}:{label:string;value:string}){return <Surface><div className="text-xs uppercase tracking-wider text-muted-foreground">{label}</div><div className="mt-2 text-2xl font-semibold">{value}</div></Surface>;}
