import { useEffect,useMemo,useState } from "react";
import { Download,Plus } from "lucide-react";
import { PageHeader,Surface } from "@/components/finance/PageHeader";
import { useDataRoomViewer } from "@/hooks/useDataRoomViewer";
import { vatLedgerRepository } from "@/repositories/vatLedgerRepository";
import { exportVatCsv,exportVatXlsx } from "@/services/expenses/vat-ledger-export";
import type { VatLedgerRow,VatPeriod } from "@/types/vat-ledger";
import { buildDuplicateExpensePayload } from "@/lib/vat-ledger-duplicate";
const input="rounded-lg border border-border bg-background px-3 py-2 text-sm";
export default function VatLedgerPage(){const viewer=useDataRoomViewer();const[periods,setPeriods]=useState<VatPeriod[]>([]);const[period,setPeriod]=useState("");const[rows,setRows]=useState<VatLedgerRow[]>([]);const[error,setError]=useState("");const[form,setForm]=useState({payment_date:"",supplier_name:"",gross_amount:"",description:""});
 const load=async()=>{try{const[p,l]=await Promise.all([vatLedgerRepository.periods(),vatLedgerRepository.ledger(period)]);setPeriods(p.vat_periods);setRows(l.transactions);setError("");}catch(e){setError(e instanceof Error?e.message:"VAT ledger unavailable");}};useEffect(()=>{void load();},[period]);
 const selected=useMemo(()=>periods.find(p=>p.id===period),[period,periods]);
 const create=async(e:React.FormEvent)=>{e.preventDefault();await vatLedgerRepository.create({...form,transaction_date:form.payment_date,change_reason:"Created through VAT fast entry"});setForm({payment_date:"",supplier_name:"",gross_amount:"",description:""});await load();};
 const edit=async(r:VatLedgerRow)=>{const supplier=window.prompt("Supplier name",r.supplier_name??"");if(supplier===null)return;const gross=window.prompt("Gross amount",String(r.gbp_gross_amount??r.gross_amount??""));if(gross===null)return;await vatLedgerRepository.update(r.id,{supplier_name:supplier,gross_amount:gross,change_reason:"Founder edited VAT ledger record"});await load();};
 const duplicate=async(r:VatLedgerRow)=>{await vatLedgerRepository.create(buildDuplicateExpensePayload(r));await load();};
 const archive=async(r:VatLedgerRow)=>{if(!window.confirm(`Archive ${r.name}?`))return;await vatLedgerRepository.archive(r.id,"Archived from VAT ledger");await load();};
 return <div><PageHeader eyebrow="VAT readiness" title="Historical VAT ledger" description="Manual working paper for founder review. Not an HMRC submission."/>{error&&<div role="alert" className="mb-4 rounded-lg border border-red-300 p-3">{error}</div>}
 <Surface className="mb-5"><div className="flex flex-wrap gap-3"><select className={input} value={period} onChange={e=>setPeriod(e.target.value)}><option value="">All VAT periods</option>{periods.map(p=><option key={p.id} value={p.id}>{p.start_date} to {p.end_date}{p.overdue?" · overdue":""}</option>)}</select><button className={input} onClick={()=>exportVatCsv(rows)}><Download className="mr-2 inline h-4 w-4"/>CSV</button><button className={input} onClick={()=>void exportVatXlsx(rows,selected)}><Download className="mr-2 inline h-4 w-4"/>XLSX</button></div></Surface>
 {viewer?.canWriteFinance&&<Surface className="mb-5"><form onSubmit={create} className="grid gap-3 md:grid-cols-5"><input required type="date" className={input} value={form.payment_date} onChange={e=>setForm({...form,payment_date:e.target.value})}/><input required className={input} placeholder="Supplier" value={form.supplier_name} onChange={e=>setForm({...form,supplier_name:e.target.value})}/><input required inputMode="decimal" className={input} placeholder="Gross amount" value={form.gross_amount} onChange={e=>setForm({...form,gross_amount:e.target.value})}/><input className={input} placeholder="Short description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><button className="rounded-lg bg-brand-orange px-3 py-2 text-sm font-semibold text-white"><Plus className="mr-2 inline h-4 w-4"/>Save pending review</button></form></Surface>}
 <Surface><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{["Tax point","Supplier","Description","Net","VAT","Gross","Treatment","Founder paid","Recoverable VAT","Evidence","Review","Warnings","Actions"].map(h=><th className="p-2" key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t border-border"><td className="p-2">{r.transaction_date??"—"}</td><td className="p-2">{r.supplier_name??"—"}</td><td className="p-2">{r.description??r.name}</td><td className="p-2">{String(r.gbp_net_amount??r.net_amount??"—")}</td><td className="p-2">{String(r.gbp_vat_amount??r.vat_amount??"—")}</td><td className="p-2">{String(r.gbp_gross_amount??r.gross_amount??"—")}</td><td className="p-2">{r.vat_treatment??"Pending"}</td><td className="p-2">{r.founder_paid==null?"—":r.founder_paid?"Yes":"No"}</td><td className="p-2">{String(r.recoverable_vat_amount??"—")}</td><td className="p-2">{r.evidence_files.length}</td><td className="p-2">{r.vat_review_status??"Pending"}</td><td className="p-2 text-brand-coral">{r.warnings.join(", ")||"—"}</td><td className="p-2">{viewer?.canWriteFinance&&<div className="flex gap-1"><button className={input} onClick={()=>void edit(r)}>Edit</button><button className={input} onClick={()=>void duplicate(r)}>Duplicate</button><button className={input} onClick={()=>void archive(r)}>Archive</button></div>}</td></tr>)}</tbody></table></div></Surface></div>}
