import { useCallback,useEffect,useState,type FormEvent } from "react";
import { Download,Eye,Paperclip,Trash2,Upload } from "lucide-react";
import { PageHeader,Surface } from "@/components/finance/PageHeader";
import { Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle } from "@/components/ui/dialog";
import { financeComplianceRepository } from "@/repositories/financeComplianceRepository";
import { evidenceRepository } from "@/repositories/evidenceRepository";
import { evidenceService } from "@/services/evidence/evidence.service";
import { documentApiErrorMessage } from "@/services/evidence/document-upload";
import { filingEvidencePurposes,type DocumentUploadInput,type FilingEvidencePurpose } from "@/types/evidence";
import type { VatFiling,VatFilingEvidence } from "@/types/finance-compliance";

const corePurposes:ReadonlySet<FilingEvidencePurpose>=new Set(["hmrc_submitted_vat_return","vat_return_submission_confirmation","vat_return_calculation_export"]);
const purposeLabels:Record<FilingEvidencePurpose,string>={hmrc_submitted_vat_return:"HMRC submitted VAT return",vat_return_submission_confirmation:"QuickFile MTD submission confirmation",vat_return_filed_summary:"QuickFile filed VAT return summary",vat_return_calculation_export:"QuickFile VAT calculation backing export",accounting_export_snapshot:"Financial OS accounting export snapshot",hmrc_obligation_confirmation:"HMRC obligation confirmation",other_vat_filing_support:"Other support"};
const sources=["HMRC / GOV.UK","QuickFile","KLPS / Financial OS","Other"];
const date=(value:string)=>new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"long",year:"numeric"}).format(new Date(`${value.slice(0,10)}T00:00:00Z`));
const input="mt-1 w-full rounded-lg border border-border bg-background px-3 py-2 text-sm";

export default function VatFilingsPage(){
  const[filings,setFilings]=useState<VatFiling[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
  const[target,setTarget]=useState<VatFiling|null>(null);
  const load=useCallback(async()=>{try{setFilings(await financeComplianceRepository.filings());setError("");}catch(reason){setError(reason instanceof Error?reason.message:"VAT filings unavailable");}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);
  return <div><PageHeader eyebrow="Finance Compliance" title="VAT Filings" description="Immutable submitted VAT returns and their canonical private evidence packs."/>
    {error&&<div role="alert" className="mb-4 text-brand-coral">{error}</div>}{loading&&<p className="text-sm text-muted-foreground">Loading VAT filings…</p>}
    <div className="space-y-5">{filings.map(filing=><FilingCard filing={filing} key={filing.id} upload={()=>setTarget(filing)} reload={load}/>)}</div>
    {!loading&&!filings.length&&!error&&<Surface><p className="text-sm text-muted-foreground">No immutable VAT filing records are available.</p></Surface>}
    <UploadFilingEvidence filing={target} close={()=>setTarget(null)} complete={async()=>{setTarget(null);await load();}}/>
  </div>;
}

function FilingCard({filing,upload,reload}:{filing:VatFiling;upload:()=>void;reload:()=>Promise<void>}){
  const present=new Set(filing.evidence.map(item=>item.filing_evidence_purpose));const complete=[...corePurposes].every(value=>present.has(value));
  const access=async(item:VatFilingEvidence,action:"view"|"download")=>{const result=await evidenceRepository.accessDocument(item.id,action);window.open(result.signed_url,"_blank","noopener,noreferrer");};
  const unlink=async(item:VatFilingEvidence)=>{if(!window.confirm(`Unlink “${item.title}” from ${filing.obligation_reference}? The immutable filing will not be changed.`))return;await evidenceRepository.unlink(item.id,item.link_id);await reload();};
  return <Surface><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">{filing.obligation_reference}</div><h2 className="mt-1 text-xl font-semibold">{date(filing.start_date)} to {date(filing.end_date)}</h2><p className="mt-1 text-sm text-muted-foreground">Submitted {date(filing.submitted_at)} · {filing.submission_method} · {filing.result.replaceAll("_"," ").toUpperCase()}</p></div><div className="flex gap-2"><span className={`rounded-full px-3 py-1 text-xs font-semibold ${complete?"bg-brand-sage/20 text-green-800":"bg-amber-100 text-amber-900"}`}>Evidence pack: {complete?"COMPLETE":"INCOMPLETE"}</span><button type="button" onClick={upload} className="inline-flex items-center gap-2 rounded-lg bg-brand-orange px-3 py-2 text-xs font-semibold text-primary-foreground"><Upload className="h-4 w-4"/>Upload filing evidence</button></div></div>
    <div className="mt-5 grid gap-4 lg:grid-cols-2"><EvidenceChecklist title="Required core evidence" purposes={[...corePurposes]} present={present}/><EvidenceChecklist title="Optional supporting evidence" purposes={filingEvidencePurposes.filter(value=>!corePurposes.has(value))} present={present}/></div>
    <div className="mt-5 space-y-2"><h3 className="font-semibold">Linked evidence</h3>{filing.evidence.length?filing.evidence.map(item=><div key={item.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-border p-3"><div><div className="font-medium">{item.title}</div><div className="text-xs text-muted-foreground">{purposeLabels[item.filing_evidence_purpose]} · {item.source_organisation??"Source not recorded"}</div></div><div className="flex gap-2"><button onClick={()=>void access(item,"view")} className="inline-flex items-center gap-1 text-xs text-blue-600"><Eye className="h-4 w-4"/>View</button><button onClick={()=>void access(item,"download")} className="inline-flex items-center gap-1 text-xs text-blue-600"><Download className="h-4 w-4"/>Download</button><button onClick={()=>void unlink(item)} className="inline-flex items-center gap-1 text-xs text-brand-coral"><Trash2 className="h-4 w-4"/>Unlink</button></div></div>):<p className="text-sm text-muted-foreground">No evidence linked yet.</p>}</div>
  </Surface>;
}
function EvidenceChecklist({title,purposes,present}:{title:string;purposes:readonly FilingEvidencePurpose[];present:Set<FilingEvidencePurpose>}){return <section><h3 className="text-sm font-semibold">{title}</h3><ul className="mt-2 space-y-1 text-sm">{purposes.map(value=><li key={value} className="flex items-center gap-2"><Paperclip className="h-3.5 w-3.5"/><span>{purposeLabels[value]}</span><span className={present.has(value)?"text-green-700":"text-muted-foreground"}>{present.has(value)?"Present":"Missing"}</span></li>)}</ul></section>;}

function UploadFilingEvidence({filing,close,complete}:{filing:VatFiling|null;close:()=>void;complete:()=>Promise<void>}){
  const[file,setFile]=useState<File|null>(null),[purpose,setPurpose]=useState<FilingEvidencePurpose|"">(""),[title,setTitle]=useState(""),[documentDate,setDocumentDate]=useState(""),[source,setSource]=useState(""),[description,setDescription]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const submit=async(event:FormEvent)=>{event.preventDefault();if(!filing||!file||!purpose)return;setBusy(true);setError("");try{await evidenceService.uploadDocument({file,title,document_category:"Finance",document_date:documentDate||undefined,description:description||undefined,source_organisation:source||undefined,linked_entity_type:"vat_filing",linked_entity_id:filing.id,relationship:purpose,filing_evidence_purpose:purpose} as DocumentUploadInput);await complete();setFile(null);setPurpose("");setTitle("");setDocumentDate("");setSource("");setDescription("");}catch(reason){setError(documentApiErrorMessage(reason));}finally{setBusy(false);}};
  return <Dialog open={Boolean(filing)} onOpenChange={open=>{if(!open)close();}}><DialogContent className="max-w-2xl"><DialogHeader><DialogTitle>Upload filing evidence</DialogTitle><DialogDescription>The VAT filing target is fixed and cannot be edited.</DialogDescription></DialogHeader>{filing&&<form onSubmit={submit} className="space-y-4"><div className="rounded-lg border border-border bg-muted/40 p-3 text-sm"><strong>{filing.obligation_reference}</strong><div>{date(filing.start_date)} to {date(filing.end_date)}</div><div className="text-muted-foreground">Submitted {date(filing.submitted_at)} · {filing.submission_method} · {filing.result}</div></div><label className="block text-sm">File *<input required type="file" accept=".pdf,.png,.jpg,.jpeg,.csv,.txt,.docx,.xlsx,.pptx" className={input} onChange={event=>setFile(event.target.files?.[0]??null)}/></label><label className="block text-sm">Evidence purpose *<select required className={input} value={purpose} onChange={event=>setPurpose(event.target.value as FilingEvidencePurpose)}><option value="">Select purpose</option>{filingEvidencePurposes.map(value=><option key={value} value={value}>{purposeLabels[value]}</option>)}</select></label><label className="block text-sm">Document title *<input required className={input} value={title} onChange={event=>setTitle(event.target.value)}/></label><div className="grid gap-3 sm:grid-cols-2"><label className="block text-sm">Document date<input type="date" className={input} value={documentDate} onChange={event=>setDocumentDate(event.target.value)}/></label><label className="block text-sm">Source organisation<select className={input} value={source} onChange={event=>setSource(event.target.value)}><option value="">Select source</option>{sources.map(value=><option key={value}>{value}</option>)}</select></label></div><label className="block text-sm">Description / notes<textarea className={`${input} min-h-24`} value={description} onChange={event=>setDescription(event.target.value)}/></label>{error&&<div role="alert" className="text-sm text-brand-coral">{error}</div>}<div className="flex justify-end gap-2"><button type="button" onClick={close} className="rounded-lg border border-border px-4 py-2 text-sm">Cancel</button><button disabled={busy||!file||!purpose||!title.trim()} className="rounded-lg bg-brand-orange px-4 py-2 text-sm font-semibold text-primary-foreground disabled:opacity-50">{busy?"Uploading…":"Upload filing evidence"}</button></div></form>}</DialogContent></Dialog>;
}
