export type DisclosureStatus = "verified" | "completed" | "in_progress" | "planned" | "not_evidenced";

export const investorDisclosure = {
  version: "1.0",
  asOf: "30 September 2026",
  company: {
    legalName: "KIDS, LADIES & PARENTS, SPECIALISTS LTD",
    tradingName: "KLPS",
    companyNumber: "16436591",
    companyType: "Private company limited by shares",
    companyStatus: "Active",
    jurisdiction: "United Kingdom",
    stage: "Pre-revenue · product development",
  },
  capTable: {
    holdings: [{ shareholder: "Emma Mendez", shareClass: "Ordinary", shares: 1, ownership: 100, votingRights: 100, nominalValue: 1 }],
    totalShares: 1,
    totalNominalCapital: 1,
    externalInvestors: "None",
    optionPool: "None",
    convertibles: "None",
    note: "No completed share subdivision is reflected. Illustrative fundraising scenarios do not alter current ownership.",
  },
  commercialForecast: {
    cohort: "Controlled Founding 50 commercial pilot",
    customers: 50,
    forecastSales: 9125,
    estimatedDirectCostPerUnit: 60,
    forecastDirectCosts: 3000,
    forecastGrossContribution: 6125,
    introductoryPriceRange: "£150–£200",
    qualification: "Planning forecast, not contracted revenue or existing sales. Unit costs will be refined when production quotations are confirmed.",
  },
  twelveMonthForecast: {
    source: "Investor-safe extract from the Start Up Loan cash-flow forecast",
    periodLabels: ["M1", "M2", "M3", "M4", "M5", "M6", "M7", "M8", "M9", "M10", "M11", "M12"],
    sales: [450, 600, 800, 700, 700, 875, 800, 800, 1000, 1000, 800, 600],
    directCosts: [180, 240, 300, 240, 240, 300, 240, 240, 300, 300, 240, 180],
    grossContribution: [270, 360, 500, 460, 460, 575, 560, 560, 700, 700, 560, 420],
    qualification: "Forward-looking planning assumptions prepared for the Start Up Loan application. The forecast is not actual trading, contracted revenue or guaranteed performance. Pending loan proceeds are not treated as received in this investor disclosure.",
  },
  funding: {
    receivedExternalInvestment: 0,
    startUpLoan: { amount: 7000, status: "in_progress" as DisclosureStatus, statement: "Application materials and supporting forecast prepared; no loan proceeds are treated as received." },
    seis: { status: "in_progress" as DisclosureStatus, statement: "Investment-readiness work is underway. No SEIS Advance Assurance or investor commitment is claimed." },
    equityRaise: { status: "planned" as DisclosureStatus, statement: "No external equity has been issued. Investor materials, financial model and due-diligence data room are being prepared for KLPS's first external raise." },
    unconfirmedFundingTreatment: "Applications, grants, investment discussions and borrowing are excluded from cash until received.",
  },
  useOfFunds: [
    { item: "Ignitec Bristol product-development workshop", amount: 2550 },
    { item: "Workshop travel", amount: 450 },
    { item: "SEIS investment-readiness support", amount: 1194 },
    { item: "10 prototype and pilot garments", amount: 1000 },
    { item: "Prototype iteration, replacement materials and testing", amount: 1806 },
  ],
  currentFinancialPosition: { founderSalary: 0, employees: 0, manufacturingPremises: "None", externalEquityRaised: 0 },
  financeAndCompliance: "Business banking and accounting infrastructure established. VAT registered and filings maintained through QuickFile. Detailed banking, tax and accounting records are retained within controlled founder records and can be provided during due diligence where appropriate.",
  cashPosition: {
    status: "not_evidenced" as DisclosureStatus,
    statement: "Current cash and cash-only runway are not published in this v1.0 investor snapshot. Planned or pending funding is not substituted for cash.",
  },
  intellectualProperty: "KLPS maintains dated engineering, product-development and research records as the technical architecture develops. Formal protection, ownership documentation and freedom-to-operate requirements will be reviewed as the product progresses toward commercial manufacture. No registered patent is currently claimed.",
  readiness: [
    { area: "Corporate", items: [["UK limited company", true], ["Founder-controlled", true], ["100% founder ownership", true], ["Business banking established", true]] },
    { area: "Finance", items: [["Accounting infrastructure established", true], ["VAT registered", true], ["12-month financial forecast", true], ["£7k Start Up Loan application in progress", false]] },
    { area: "Investment", items: [["Investor data room established", true], ["Cap table established", true], ["First raise preparation underway", true], ["SEIS preparation underway", false]] },
    { area: "Commercial", items: [["Founding 50 commercial model established", true], ["£150–£200 introductory pricing model", true], ["50-customer controlled pilot forecast", true], ["Manufacturing cost validation in progress", false]] },
    { area: "Product", items: [["Early technical development completed", true], ["Prototype pathway established", true], ["External engineering engagement underway", true], ["Final manufacturing specification pending", false]] },
  ],
  governanceNote: "This disclosure is purpose-built for authorised investor review. Founder-only Financial OS records, account details, personal credit information, internal scenarios and private notes are excluded.",
  disclosureBasis: "Information reflects the company's position as at 30 September 2026. Applications and planned financing are identified as such and should not be interpreted as secured or committed funding.",
} as const;
