import {useEffect,useState,type FormEvent} from 'react';
import {authenticatedApi} from '@/lib/authenticated-api';
import {evidenceRepository} from '@/repositories/evidenceRepository';
type State={channel:null|{id:string;provider:string;stage:string;event_date:string|null;evidence_id:string|null;verified:boolean};events:{id:string;description:string;occurred_on:string|null;communication_status:string;evidence_current:boolean}[];update_categories:string[]};
export function AlmaOutreachWorkspace(){
  const [data,setData]=useState<State|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const [evidence,setEvidence]=useState<{id:string;title:string}[]>([]);
  const load=async()=>setData(await authenticatedApi<State>('/api/finance/outreach'));
  useEffect(()=>{let active=true;authenticatedApi<State>('/api/finance/outreach').then(d=>{if(active)setData(d)}).catch(()=>{if(active)setError('The private outreach workspace is unavailable while the backend release is pending.')});return()=>{active=false}},[]);
  const prepare=async()=>{try{const r=await authenticatedApi<{evidence:{id:string;title:string}[]}>('/api/finance/evidence?limit=500');setEvidence(r.evidence)}catch{setError('Unable to load private evidence.')}};
  const save=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!data?.channel)return;setBusy(true);setError('');const form=e.currentTarget;try{await authenticatedApi(`/api/finance/outreach/${data.channel.id}/updates`,{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(form)))});form.reset();await load()}catch(e){setError(e instanceof Error?e.message:'Unable to record update')}finally{setBusy(false)}};
  const download=async()=>{if(!data?.channel?.evidence_id)return;setBusy(true);try{const r=await evidenceRepository.accessDocument(data.channel.evidence_id,'download');const a=document.createElement('a');a.href=r.signed_url;a.download='Alma-distribution-source.pdf';a.click()}catch{setError('Unable to retrieve the restricted original.')}finally{setBusy(false)}};
  return <section className="rounded-lg border border-border bg-background p-5 text-foreground"><p className="text-xs uppercase text-muted-foreground">Founder / admin only</p><h3 className="mt-2 text-2xl font-semibold">Alma Angels</h3>{error&&<p role="alert" className="mt-3 text-sm">{error}</p>}{!data&&!error&&<p>Loading private outreach record…</p>}{data&&!data.channel&&<p className="mt-3">No canonical Alma distribution record is available yet.</p>}{data?.channel&&<><p className="mt-3 font-medium">{data.channel.stage}</p><p className="mt-2 text-sm">KLPS venture shared with Alma community · {data.channel.event_date}</p><p className="mt-3 text-sm">Distribution does not establish investor interest, meetings, diligence, proposals, commitments or investment. Individual angels decide independently; no interest is guaranteed.</p><p className="mt-2 text-sm">Community size and general ticket sizes are source context, not KLPS leads or a funding range. Record individual contacts only when a real interaction occurs.</p><button className="mt-3 rounded border border-border px-3 py-2 text-sm" disabled={busy} onClick={()=>void download()}>Download restricted original email</button><details className="mt-5" onToggle={e=>{if(e.currentTarget.open&&evidence.length===0)void prepare()}}><summary className="cursor-pointer">Record a significant update for later founder review</summary><form className="mt-3 grid gap-3" onSubmit={e=>void save(e)}><label>Category<select name="category" className="block w-full rounded border bg-background p-2">{data.update_categories.map(c=><option key={c}>{c}</option>)}</select></label><label>Milestone date<input type="date" name="occurred_on" required className="block rounded border bg-background p-2"/></label><label>Supporting evidence<select name="evidence_id" required className="block w-full rounded border bg-background p-2"><option value="">Select verified evidence</option>{evidence.map(e=><option key={e.id} value={e.id}>{e.title}</option>)}</select></label><label>Factual milestone<textarea name="description" required maxLength={10000} className="block w-full rounded border bg-background p-2"/></label><p className="text-sm">Saved updates remain drafts requiring founder approval. This workspace cannot send to Alma or advance the investor pipeline.</p><button className="rounded border p-2" disabled={busy}>Save update candidate</button></form></details><ol className="mt-4 space-y-3">{data.events.map(e=><li className="rounded border border-border p-3 text-sm" key={e.id}><p>{e.description}</p><p className="mt-2 text-xs">{e.occurred_on} · {e.communication_status}{!e.evidence_current?' · EVIDENCE REVIEW REQUIRED':''}</p></li>)}</ol></>}</section>;
}
