import { evidenceRepository } from '@/repositories/evidenceRepository';
import { useEffect, useState, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { readinessApi, type Readiness, type Requirement, type OwnershipSnapshot, type Calculation, type SubdivisionReview } from '@/services/fundraising-readiness';

const field = 'w-full rounded border border-border bg-background p-2 text-sm text-foreground';
const button = 'rounded border border-border px-3 py-2 text-sm font-medium disabled:opacity-50';
const money = (value:number|string|null|undefined) => value == null ? 'Not set' : new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP',maximumFractionDigits:2}).format(Number(value));
const pct = (value:number|undefined) => value === undefined ? 'Unavailable' : `${(value*100).toFixed(2)}%`;
const message = (error:unknown) => error instanceof Error ? error.message : 'The request failed. Please reload and try again.';

export function FounderCatalystWorkspace({ownershipOnly=false}:{ownershipOnly?:boolean}) {
  const [data,setData] = useState<Readiness|null>(null);
  const [error,setError] = useState('');
  const [busy,setBusy] = useState(false);
  const [tab,setTab] = useState(ownershipOnly ? 'Ownership' : 'Readiness');
  const [selected,setSelected] = useState<Requirement|null>(null);
  const load = async () => setData(await readinessApi.get());
  useEffect(() => { let active=true; readinessApi.get().then(value => {if(active)setData(value);}).catch(e => {if(active)setError(message(e));}); return () => {active=false;}; },[]);
  const run = async (action:()=>Promise<unknown>) => {
    setBusy(true);setError('');
    try {await action();await load();setSelected(null);} catch(e) {setError(message(e));} finally {setBusy(false);}
  };
  return <section className="mb-6 rounded-lg border border-border bg-background p-5 text-foreground">
    <header><p className="text-xs uppercase tracking-wider text-muted-foreground">Founder / admin only</p><h3 className="mt-2 text-2xl font-semibold">{ownershipOnly ? 'Company ownership and fundraising scenarios' : 'FounderCatalyst'}</h3><p className="mt-2 text-sm text-muted-foreground">First external fundraising preparation / SEIS readiness</p></header>
    {error && <div role="alert" className="my-4 rounded border border-amber-500 p-3 text-sm">{error}<p className="mt-1">The workspace could not be loaded. Retry or contact your administrator.</p><button className={button} onClick={()=>void run(load)} disabled={busy}>Retry</button></div>}
    {!data && !error && <p role="status" className="mt-4">Loading private workspace…</p>}
    {data && !data.engagement && <div className="mt-5 space-y-3"><p>Create the internal engagement and checklist from the approved founder decision. This records preparation only.</p><button className={button} disabled={busy} onClick={()=>void run(readinessApi.initialise)}>Create internal readiness record</button></div>}
    {data?.engagement && <>
      <dl className="my-5 grid gap-4 sm:grid-cols-3"><div><dt className="text-xs text-muted-foreground">Current strategy</dt><dd>{data.engagement.purpose}</dd></div><div><dt className="text-xs text-muted-foreground">Agreed cost, excluding VAT</dt><dd>{money(data.engagement.budget_ex_vat)} + VAT</dd></div><div><dt className="text-xs text-muted-foreground">Process status</dt><dd>{data.engagement.status}</dd></div></dl>
      <p className="text-sm text-muted-foreground">{data.engagement.price_basis}</p>
      <p className="mt-2 text-sm text-muted-foreground">Service purchased: {data.engagement.service_purchased ?? 'Provider scope awaiting evidence'}. Start date: {data.engagement.start_date ?? 'Not evidenced'}. Payment status: see canonical payment evidence in the activity record; no payment is inferred.</p>
      <details className="mt-3"><summary className="cursor-pointer text-sm">Update process status</summary><form className="mt-3 grid gap-3 sm:grid-cols-2" onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);void run(()=>readinessApi.update(data.engagement!.id,{...Object.fromEntries(form),version:data.engagement!.version,evidence_id:form.get('evidence_id') || null}));}}><label className="text-sm">Status<select className={field} name="status" defaultValue={data.engagement.status}>{['Preparing','In progress','Awaiting founder','Awaiting provider','Complete','Paused'].map(s=><option key={s}>{s}</option>)}</select></label><label className="text-sm">Change reason<input className={field} name="reason" required/></label><label className="text-sm">Service purchased<input className={field} name="service_purchased" defaultValue={data.engagement.service_purchased ?? ''}/></label><label className="text-sm">Start date<input className={field} name="start_date" type="date" defaultValue={data.engagement.start_date?.slice(0,10) ?? ''}/></label><EvidencePicker/><p className="text-xs text-muted-foreground">Completion requires resolved requirements and verified evidence. Process completion does not mean SEIS approval.</p><button className={button} disabled={busy}>Save process status</button></form></details>
      <div role="tablist" aria-label="FounderCatalyst workspace" className="my-5 flex flex-wrap gap-2">{['Readiness','Ownership','Scenarios','Activity'].map(name=><button key={name} role="tab" aria-selected={tab===name} className={`${button} ${tab===name ? 'bg-muted' : ''}`} onClick={()=>setTab(name)}>{name}</button>)}</div>
      {tab==='Readiness' && <div role="tabpanel">
        {data.subdivision_review?.review_evidence_id && <ReviewPackButton evidenceId={data.subdivision_review.review_evidence_id}/>} 
        <p className="mb-4 text-sm">Clean corporate evidence → verified cap table → SEIS readiness → credible forecast and pitch deck → investor readiness → first raise.</p>
        <p className="mb-4 text-sm text-muted-foreground">A completed checklist does not establish HMRC approval. Each requirement retains its source and review record.</p>
        <div className="space-y-3">{data.requirements.map(item=><article key={item.id} className="rounded border border-border p-4">
          <div className="flex flex-wrap items-start justify-between gap-3"><h4 className="font-medium">{item.code} · {item.title}</h4><span className="text-xs">{item.classification}</span></div>
          {item.classification==='AVAILABLE + VERIFIED' && (item.evidence_status!=='Verified' || item.evidence_document_status!=='Active' || item.evidence_version!==item.reviewed_evidence_version) && <p role="alert" className="mt-2 text-amber-600">Evidence verification has changed. Review this requirement again.</p>}
          <p className="mt-2 text-sm">{item.next_action}</p>
          <dl className="mt-3 grid gap-2 text-xs text-muted-foreground sm:grid-cols-2"><div><dt>Canonical location</dt><dd>{item.canonical_location}</dd></div><div><dt>Required document</dt><dd>{item.required_document}</dd></div><div><dt>Owner</dt><dd>{item.owner}</dd></div><div><dt>Dependencies</dt><dd>{item.dependency || 'None recorded'}</dd></div><div><dt>Source</dt><dd>{item.source}</dd></div><div><dt>Evidence</dt><dd>{item.evidence_title ?? 'Not linked'}</dd></div></dl>
          {item.notes && <p className="mt-3 whitespace-pre-wrap text-sm">{item.notes}</p>}
          <button className={`${button} mt-3`} disabled={busy} onClick={()=>setSelected(item)}>Review requirement</button>
        </article>)}</div>
        {selected && <ReviewForm key={selected.id} requirement={selected} classifications={data.classifications} busy={busy} cancel={()=>setSelected(null)} submit={input=>run(()=>readinessApi.review(selected.id,input))}/>}
      </div>}
      {tab==='Ownership' && <Ownership snapshots={data.ownership} proposal={data.subdivision_review}/>}
      {tab==='Scenarios' && <div role="tabpanel"><p className="mb-3 text-sm">No final round size, valuation or equity offer is selected. £250,000 is planning only; £260,000 is a provider-suggested alternative. A saved scenario cannot change actual ownership or received investment.</p><ScenarioForm busy={busy} snapshots={data.ownership} submit={input=>run(()=>readinessApi.scenario(data.engagement!.id,input))}/><div className="mt-5 space-y-4">{data.scenarios.length===0 && <p>No scenarios saved.</p>}{data.scenarios.map(s=><article key={s.id} className="rounded border border-border p-4"><h4 className="font-semibold">{s.name} · SCENARIO</h4><p className="mt-2 text-sm">Proposed investment: {money(s.proposed_investment)}. Pre-money valuation: {money(s.pre_money_valuation)}.</p>{s.baseline_review_required && <p role="alert" className="mt-2 text-amber-600">Baseline evidence requires review. Share-count outputs are unavailable.</p>}<ScenarioResults value={s.calculation}/><p className="mt-2 whitespace-pre-wrap text-sm text-muted-foreground">{s.notes}</p></article>)}</div></div>}
      {tab==='Activity' && <div role="tabpanel"><p className="mb-3 text-sm">Append-only decisions, correspondence, document versions and milestones. Recording an event does not send a message, make a payment or submit a filing. Use evidence references for sensitive documents.</p><ActivityForm busy={busy} submit={input=>run(()=>readinessApi.activity(data.engagement!.id,input))}/><ol className="mt-5 space-y-3">{data.activity.map(event=><li key={event.id} className="rounded border border-border p-3"><div className="text-xs text-muted-foreground">{event.kind.replace(/_/g,' ')} · recorded {new Date(event.recorded_at).toLocaleString('en-GB')}{event.occurred_on ? ` · occurred ${event.occurred_on.slice(0,10)}` : ''}</div><p className="mt-2 whitespace-pre-wrap text-sm">{event.description}</p><p className="mt-2 text-xs text-muted-foreground">Source: {event.source}{event.evidence_id ? ` · Evidence: ${event.evidence_id}` : ''}</p></li>)}</ol></div>}
    </>}
  </section>;
}

function EvidencePicker({selected=null}:{selected?:string|null}) {
  const [items,setItems]=useState<{id:string;title:string;evidence_code?:string}[]>([]);
  const [error,setError]=useState('');
  useEffect(()=>{let active=true;readinessApi.evidence().then(result=>{if(active)setItems(result.evidence);}).catch(e=>{if(active)setError(message(e));});return ()=>{active=false;};},[]);
  return <label className="mt-3 block text-sm">Canonical evidence<select className={field} name="evidence_id" defaultValue={selected ?? ''}><option value="">Not linked</option>{selected && !items.some(item=>item.id===selected) && <option value={selected}>Current linked evidence</option>}{items.map(item=><option key={item.id} value={item.id}>{item.evidence_code ? `${item.evidence_code} · ` : ''}{item.title}</option>)}</select>{error && <span role="alert" className="text-xs">{error}</span>}<span className="text-xs text-muted-foreground">Latest 500 records. Register missing documents in Finance OS evidence.</span></label>;
}
function ReviewForm({requirement:r,classifications,busy,cancel,submit}:{requirement:Requirement;classifications:string[];busy:boolean;cancel:()=>void;submit:(input:Record<string,unknown>)=>Promise<void>}) {
  const save = (event:FormEvent<HTMLFormElement>) => {event.preventDefault();const form=new FormData(event.currentTarget);void submit({...Object.fromEntries(form),version:r.version,evidence_id:form.get('evidence_id') || null,review_confirmed:form.get('review_confirmed')==='on'});};
  return <form onSubmit={save} className="fixed inset-x-3 bottom-3 z-50 max-h-[85vh] overflow-y-auto rounded-lg border border-border bg-background p-5 shadow-xl sm:inset-x-auto sm:right-5 sm:w-[520px]" aria-label={`Review ${r.code}`}>
    <h4 className="mb-3 font-semibold">Review {r.code}</h4><label className="block text-sm">Classification<select className={field} name="classification" defaultValue={r.classification}>{classifications.map(s=><option key={s}>{s}</option>)}</select></label>
    <label className="mt-3 block text-sm">Responsible party<input className={field} name="owner" defaultValue={r.owner} required/></label>
    <EvidencePicker selected={r.evidence_id}/>
    <label className="mt-3 block text-sm">Review notes / reason<textarea className={field} name="notes" defaultValue={r.notes} required maxLength={10000}/></label>
    <label className="mt-3 block text-sm">Next action<input className={field} name="next_action" defaultValue={r.next_action} required/></label>
    <label className="mt-3 flex gap-2 text-sm"><input type="checkbox" name="review_confirmed"/>I reviewed the linked evidence and it supports this requirement.</label>
    <div className="mt-4 flex gap-2"><button className={button} disabled={busy}>Save review</button><button className={button} type="button" onClick={cancel}>Cancel</button></div>
  </form>;
}

function Ownership({snapshots,proposal}:{snapshots:OwnershipSnapshot[];proposal?:SubdivisionReview|null}) {
  const current=snapshots.find(s=>s.scope==='ACTUAL');
  const history=snapshots.filter(s=>s.id!==current?.id);
  return <div role="tabpanel"><h4 className="font-semibold">Actual ownership</h4>{current?.usable ? <Snapshot snapshot={current}/> : <p className="mt-3 rounded border border-amber-500/40 p-4 text-sm">PENDING EVIDENCE — Current ownership has not been established here. Reconcile the register, incorporation evidence and subsequent events. The old frontend snapshot is not used as a current verified baseline.</p>}<p className="my-4 text-sm text-muted-foreground">Current ownership is assessed against the reconstructed register, primary incorporation evidence and subsequent-event confirmation. KLPS remains bootstrapped.</p>{proposal && <article className="my-4 rounded border border-amber-500 p-4"><h4 className="font-semibold">Proposed future structure — NOT CURRENT ISSUED CAPITAL</h4><p className="mt-2 text-sm">{proposal.status}</p><p className="mt-2">{proposal.shareholder} · {proposal.shares.toLocaleString("en-GB")} {proposal.share_class} shares · £{proposal.nominal_value.toFixed(4)} nominal per share · {pct(proposal.ownership)}</p><p className="mt-2 text-sm">Aggregate nominal capital {money(proposal.nominal_capital)} · paid {money(proposal.amount_paid)} · unpaid {money(proposal.amount_unpaid)}.</p><p className="mt-2 text-sm">NOT PASSED · NOT EXECUTED · NOT FILED. No investment, dilution or new shareholder. All execution and filing dates remain unset.</p><p className="mt-2 text-sm">FC05: Approved in principle — pending FounderCatalyst/final execution review.</p>{proposal.review_evidence_id && <ReviewPackButton evidenceId={proposal.review_evidence_id}/>}</article>}<h4 className="font-semibold">Historical snapshots</h4>{history.map(s=><Snapshot key={s.id} snapshot={s} historical/>)}{history.length===0 && <p className="mt-2 text-sm">No canonical historical snapshot registered yet. Original incorporation evidence remains the source for reconciliation.</p>}</div>;
}
function Snapshot({snapshot:s,historical=false}:{snapshot:OwnershipSnapshot;historical?:boolean}) {
  return <article className="my-3 rounded border border-border p-4"><p className="text-sm">{historical ? 'HISTORICAL' : s.scope} · {s.effective_date.slice(0,10)} · {s.usable ? s.verification_status : 'REVIEW REQUIRED'}</p>{!s.usable ? <p>{s.review_required}</p> : <div className="mt-3 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Shareholder','Type','Class','Shares','Ownership','Nominal / share','Paid','Unpaid','Acquired','Voting rights'].map(t=><th className="p-2" key={t}>{t}</th>)}</tr></thead><tbody>{s.calculated?.holdings.map((h,index)=><tr key={index}>{[h.shareholder,h.shareholder_type,h.share_class,h.shares,pct(h.ownership),money(h.nominal_value),money(h.amount_paid),money(h.amount_unpaid),h.acquisition_date,h.voting_rights].map((v,i)=><td className="border-t border-border p-2" key={i}>{v}</td>)}</tr>)}</tbody></table><p className="mt-2">Total: {s.calculated?.shares} shares · {pct(s.calculated?.total_ownership)} · nominal capital {money(s.calculated?.nominal_capital)}</p></div>}<p className="mt-3 text-xs text-muted-foreground">Evidence: {s.evidence_id} · version {s.evidence_version}. {s.review_notes}</p></article>;
}
function ScenarioForm({busy,snapshots,submit}:{busy:boolean;snapshots:OwnershipSnapshot[];submit:(input:Record<string,unknown>)=>Promise<void>}) {
  const save=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);void submit({name:form.get('name'),proposed_investment:form.get('investment') ? Number(form.get('investment')) : null,pre_money_valuation:form.get('valuation') ? Number(form.get('valuation')) : null,baseline_id:form.get('baseline') || null,notes:form.get('notes')});};
  return <form onSubmit={save} className="grid gap-3 rounded border border-border p-4 sm:grid-cols-2"><label className="text-sm">Scenario name<input className={field} name="name" required/></label><label className="text-sm">Verified ownership baseline<select className={field} name="baseline"><option value="">Not selected — valuation ratios only</option>{snapshots.filter(s=>s.usable).map(s=><option key={s.id} value={s.id}>{s.scope} · {s.effective_date.slice(0,10)}</option>)}</select></label><label className="text-sm">Proposed investment (£, optional)<input className={field} name="investment" type="number" min="0.01" step="0.01"/></label><label className="text-sm">Pre-money valuation (£, optional)<input className={field} name="valuation" type="number" min="0.01" step="0.01"/></label><label className="text-sm sm:col-span-2">Notes<textarea className={field} name="notes" maxLength={10000}/></label><p className="text-xs text-muted-foreground sm:col-span-2">This first model handles simple priced equity. Option pools and convertible instruments require a separately specified model. Missing inputs stay unset.</p><button className={button} disabled={busy}>Save separate scenario</button></form>;
}
function ScenarioResults({value:v}:{value:Calculation}) {return <div className="mt-3 text-sm">{!v.available ? <p>{v.missing}</p> : <><p>Post-money: {money(v.post_money)} · Investor ownership: {pct(v.investor_ownership)}</p>{v.price_per_share != null && <p>Price per share: {money(v.price_per_share)} · Theoretical new shares: {v.theoretical_new_shares?.toLocaleString('en-GB')} · Post-round shares: {v.theoretical_post_round_shares?.toLocaleString('en-GB')}</p>}{v.requires_share_rounding_review && <p className="mt-2 text-amber-600">Fractional shares require rounding or separately approved corporate structuring. These are theoretical results.</p>}{v.holdings?.map((h,i)=><p key={i}>{h.shareholder}: {pct(h.before)} → {pct(h.after)}</p>)}<p className="mt-2 text-xs text-muted-foreground">{v.basis}</p></>}</div>;}
function ActivityForm({busy,submit}:{busy:boolean;submit:(input:Record<string,unknown>)=>Promise<void>}) {
  const save=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);void submit({...Object.fromEntries(form),evidence_id:form.get('evidence_id') || null,occurred_on:form.get('occurred_on') || null});};
  return <form onSubmit={save} className="grid gap-3 rounded border border-border p-4 sm:grid-cols-2"><label className="text-sm">Event type<select className={field} name="kind">{['founder_decision','provider_decision','correspondence','milestone','document_received','document_generated','supplied','approval','cost_reference','payment_reference'].map(k=><option key={k} value={k}>{k.replace(/_/g,' ')}</option>)}</select></label><label className="text-sm">Event date<input className={field} type="date" name="occurred_on"/></label><label className="text-sm">Source / canonical reference<input className={field} name="source" required/></label><EvidencePicker/><label className="text-sm sm:col-span-2">Description<textarea className={field} name="description" required maxLength={10000}/></label><p className="text-xs text-muted-foreground sm:col-span-2">Document, supply, approval and financial-reference events require evidence. Use the existing <Link to="/data-room/finance/evidence" className="underline">Finance OS evidence workspace</Link> for secure documents.</p><button className={button} disabled={busy}>Record activity</button></form>;
}

function ReviewPackButton({evidenceId}:{evidenceId:string}) {
  const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  const download=async()=>{setBusy(true);setError('');try{const result=await evidenceRepository.accessDocument(evidenceId,'download');const a=document.createElement('a');a.href=result.signed_url;a.download='KLPS-FounderCatalyst-review-pack.pdf';document.body.appendChild(a);a.click();a.remove();}catch(e){setError(message(e));}finally{setBusy(false);}};
  return <div className="my-4"><button className={button} disabled={busy} onClick={()=>void download()}>Download restricted professional-review pack</button><p className="mt-2 text-xs text-muted-foreground">Founder/admin working copy. Unsigned and unexecuted; not supplied to FounderCatalyst.</p>{error && <p role="alert">{error}</p>}</div>;
}
