import { Banknote, Check, Circle, CircleDollarSign, Landmark, ShieldCheck } from "lucide-react";
import { investorDisclosure, type DisclosureStatus } from "@/config/investorDisclosure";
import { Link } from "react-router-dom";

const pounds = (value: number) => new Intl.NumberFormat("en-GB", { style: "currency", currency: "GBP", maximumFractionDigits: 0 }).format(value);
const statusLabel: Record<DisclosureStatus, string> = { verified: "Verified", completed: "Established", in_progress: "In progress", planned: "Pre-seed preparation", not_evidenced: "Not published" };
const statusStyle: Record<DisclosureStatus, string> = { verified: "bg-emerald-50 text-emerald-800 border-emerald-200", completed: "bg-emerald-50 text-emerald-800 border-emerald-200", in_progress: "bg-amber-50 text-amber-900 border-amber-200", planned: "bg-blue-50 text-blue-800 border-blue-200", not_evidenced: "bg-slate-50 text-slate-700 border-slate-200" };

export function InvestorFinancialSnapshot() {
  const d = investorDisclosure;
  return <article className="mt-10 space-y-6 text-[#71616a]">
    <section className="rounded-2xl border border-pink-100 bg-pink-50/40 p-6 md:p-8">
      <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-medium uppercase tracking-[0.18em] text-[#b52b70]">Company &amp; Capital Snapshot</p><h2 className="mt-3 font-serif text-3xl text-[#241b20]">Founder-owned. Pre-investment. Building deliberately.</h2><p className="mt-3 text-sm">Version {d.version} · information correct as at {d.asOf}</p></div><span className="inline-flex items-center gap-2 rounded-full border border-emerald-200 bg-emerald-50 px-3 py-1.5 text-xs font-medium text-emerald-800"><ShieldCheck size={15} /> Published v{d.version}</span></div>
      <div className="mt-6 grid gap-4 sm:grid-cols-3"><Metric label="Operating position" value="Pre-revenue" note="Lean product-development stage" /><Metric label="Founding pilot" value="50 customers" note={`${pounds(d.commercialForecast.forecastSales)} forecast revenue`} /><Metric label="External equity raised" value="£0" note="First raise preparation underway" /></div>
      <p className="mt-5 text-sm"><Link className="font-medium text-[#9d245d] underline underline-offset-4" to="/data-room?folder=Company%20%26%20Legal">Review the current cap table and ownership structure</Link></p>
    </section>

    <section className="grid gap-6 lg:grid-cols-2">
      <Section icon={Landmark} title="Current financial position"><p className="font-medium text-[#241b20]">Pre-revenue · Product development</p><p className="mt-2 text-sm leading-6">KLPS is progressing through product development toward prototype validation and an initial controlled commercial cohort.</p><dl className="mt-5 grid grid-cols-2 gap-4"><Value label="Founder salary from KLPS" value={pounds(d.currentFinancialPosition.founderSalary)} /><Value label="Employees" value={String(d.currentFinancialPosition.employees)} /><Value label="Manufacturing premises" value={d.currentFinancialPosition.manufacturingPremises} /><Value label="External equity raised" value={pounds(d.currentFinancialPosition.externalEquityRaised)} /></dl></Section>
      <Section icon={Banknote} title="Funding activity"><Status label="SEIS preparation" status={d.funding.seis.status} text="Investment-readiness and SEIS preparation underway ahead of the company's first external equity raise." /><Status label="Start Up Loan" status={d.funding.startUpLoan.status} text={`£7,000 application supporting defined product-development expenditure and prototype progression. ${d.funding.startUpLoan.statement}`} /><Status label="Equity fundraising" status={d.funding.equityRaise.status} text={d.funding.equityRaise.statement} /></Section>
    </section>

    <Section icon={CircleDollarSign} title="Commercial model · Founding 50"><div className="overflow-x-auto"><table className="w-full min-w-[520px] text-left text-sm"><tbody>{[["Initial commercial cohort", `${d.commercialForecast.customers} customers`], ["Forecast revenue", pounds(d.commercialForecast.forecastSales)], ["Estimated direct cost of sales", pounds(d.commercialForecast.forecastDirectCosts)], ["Gross contribution", pounds(d.commercialForecast.forecastGrossContribution)], ["Commercial unit cost assumption", pounds(d.commercialForecast.estimatedDirectCostPerUnit)], ["Introductory price range", d.commercialForecast.introductoryPriceRange]].map(([label, value]) => <tr key={label} className="border-b border-pink-100"><th className="py-3 pr-6 font-medium text-[#71616a]">{label}</th><td className="py-3 font-semibold text-[#241b20]">{value}</td></tr>)}</tbody></table></div><p className="mt-4 text-xs leading-5">{d.commercialForecast.qualification}</p></Section>

    <Section icon={Banknote} title="Near-term capital deployment"><div className="overflow-x-auto"><table className="w-full min-w-[520px] text-left text-sm"><tbody>{d.useOfFunds.map(row => <tr key={row.item} className="border-b border-pink-100"><td className="py-3 pr-6">{row.item}</td><td className="py-3 text-right font-semibold text-[#241b20]">{pounds(row.amount)}</td></tr>)}<tr className="font-semibold text-[#241b20]"><td className="py-4">Total</td><td className="py-4 text-right">£7,000</td></tr></tbody></table></div><p className="mt-4 text-sm leading-6">This funding is intended to move KLPS through engineering development, prototype iteration and preparation for controlled wearer and commercial testing. It does not fund founder salary.</p></Section>

    <Section icon={ShieldCheck} title="Finance, commercial and product readiness"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{d.readiness.filter(group => ["Finance", "Commercial", "Product"].includes(group.area)).map(group => <div key={group.area} className="rounded-xl border border-pink-100 p-4"><h3 className="font-semibold text-[#241b20]">{group.area}</h3><ul className="mt-3 space-y-2 text-sm">{group.items.map(([label, complete]) => <li key={label} className="flex gap-2">{complete ? <Check size={16} className="mt-0.5 shrink-0 text-emerald-600" /> : <Circle size={14} className="mt-1 shrink-0 text-amber-600" />}<span>{label}</span></li>)}</ul></div>)}</div></Section>

    <footer className="rounded-xl border border-pink-100 bg-pink-50/50 p-4 text-xs leading-5"><strong className="text-[#241b20]">Disclosure basis:</strong> {d.disclosureBasis}</footer>
  </article>;
}

function Section({ icon: Icon, title, children }: { icon: typeof Landmark; title: string; children: React.ReactNode }) { return <section className="rounded-2xl border border-pink-100 p-6"><h2 className="flex items-center gap-2 font-semibold text-[#241b20]"><Icon size={18} /> {title}</h2><div className="mt-5">{children}</div></section>; }
function Metric({ label, value, note }: { label: string; value: string; note: string }) { return <div className="rounded-xl border border-pink-100 bg-white p-4"><p className="text-xs uppercase tracking-wider text-[#9b8993]">{label}</p><p className="mt-2 text-2xl font-semibold text-[#241b20]">{value}</p><p className="mt-1 text-xs">{note}</p></div>; }
function Value({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs uppercase tracking-wider text-[#9b8993]">{label}</dt><dd className="mt-1 font-medium text-[#241b20]">{value}</dd></div>; }
function Status({ label, status, text }: { label: string; status: DisclosureStatus; text: string }) { return <div className="mb-3 rounded-xl border border-pink-100 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="text-sm font-semibold text-[#241b20]">{label}</h3><span className={`rounded-full border px-2.5 py-1 text-[10px] font-medium uppercase tracking-wider ${statusStyle[status]}`}>{statusLabel[status]}</span></div><p className="mt-2 text-sm leading-6">{text}</p></div>; }
