import { ArrowUpRight, Banknote, Check, Circle, CircleDollarSign, Landmark, PieChart, ShieldCheck } from "lucide-react";
import { investorDisclosure, type DisclosureStatus } from "@/config/investorDisclosure";
import { Link } from "react-router-dom";

const pounds = (value: number) => new Intl.NumberFormat("en-GB", { style: "currency", currency: "GBP", maximumFractionDigits: 0 }).format(value);
const statusLabel: Record<DisclosureStatus, string> = { verified: "Verified", completed: "Established", in_progress: "In progress", planned: "Pre-seed preparation", not_evidenced: "Not published" };
const statusStyle: Record<DisclosureStatus, string> = { verified: "bg-emerald-50 text-emerald-800 border-emerald-200", completed: "bg-emerald-50 text-emerald-800 border-emerald-200", in_progress: "bg-amber-50 text-amber-900 border-amber-200", planned: "bg-blue-50 text-blue-800 border-blue-200", not_evidenced: "bg-slate-50 text-slate-700 border-slate-200" };
const readinessLinks: Record<string, { href: string; label: string }> = {
  "VAT registered": { href: "#finance-compliance", label: "View VAT and accounting basis" },
  "12-month financial forecast": { href: "#twelve-month-forecast", label: "View 12-month forecast" },
  "Founding 50 commercial model established": { href: "#founding-50", label: "View Founding 50 model" },
  "50-customer controlled pilot forecast": { href: "#founding-50", label: "View pilot forecast" },
  "External engineering engagement underway": { href: "/data-room?folder=Development%20Conversations", label: "View development conversations" },
  "Early technical development completed": { href: "/data-room/technology/mvp1-blueprint", label: "View technical blueprint" },
};

export function InvestorFinancialSnapshot() {
  const d = investorDisclosure;
  return <article className="mt-10 space-y-6 text-[#71616a]">
    <section className="rounded-2xl border border-pink-100 bg-pink-50/40 p-6 md:p-8">
      <div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-medium uppercase tracking-[0.18em] text-[#b52b70]">Company &amp; Capital Snapshot</p><h2 className="mt-3 font-serif text-3xl text-[#241b20]">Founder-owned. Pre-investment.</h2><p className="mt-3 text-sm">Version {d.version} · information correct as at {d.asOf}</p></div><span className="inline-flex items-center gap-2 rounded-full border border-emerald-200 bg-emerald-50 px-3 py-1.5 text-xs font-medium text-emerald-800"><ShieldCheck size={15} /> Published v{d.version}</span></div>
      <div className="mt-6 grid gap-4 sm:grid-cols-3"><Metric label="Operating position" value="Pre-revenue" note="Lean product-development stage" /><Metric href="#founding-50" label="Founding pilot" value="50 customers" note={`${pounds(d.commercialForecast.forecastSales)} forecast revenue · View assumptions`} /><Metric label="External equity raised" value="£0" note="First raise preparation underway" /></div>
    </section>

    <Section icon={PieChart} title="Capitalisation · actual current position">
      <div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="border-b border-pink-100 text-xs uppercase tracking-wider text-[#9b8993]"><tr>{["Shareholder", "Share class", "Shares", "Ownership", "Voting rights"].map(value => <th key={value} className="p-3 first:pl-0">{value}</th>)}</tr></thead><tbody>{d.capTable.holdings.map(holding => <tr key={holding.shareholder} className="border-b border-pink-100 text-[#241b20]"><td className="py-4 pr-3 font-medium">{holding.shareholder}</td><td className="p-3">{holding.shareClass}</td><td className="p-3">{holding.shares}</td><td className="p-3">{holding.ownership}%</td><td className="p-3">{holding.votingRights}%</td></tr>)}<tr className="font-semibold text-[#241b20]"><td className="py-4 pr-3">Total</td><td className="p-3">—</td><td className="p-3">{d.capTable.totalShares}</td><td className="p-3">100%</td><td className="p-3">100%</td></tr></tbody></table></div>
      <div className="mt-5 grid gap-2 text-sm sm:grid-cols-2 lg:grid-cols-3">{[["Founder-owned", "100%"], ["External equity raised", "£0"], ["External investors", d.capTable.externalInvestors], ["Convertible instruments", d.capTable.convertibles], ["Options issued", "None"], ["Option pool", "None currently established"], ["Preference shares", "None"], ["Previous equity rounds", "None"]].map(([label, value]) => <div key={label} className="rounded-lg bg-pink-50/60 px-3 py-2"><strong className="text-[#241b20]">{label}:</strong> {value}</div>)}</div>
      <p className="mt-4 text-xs">{d.capTable.note}</p>
    </Section>

    <section className="grid gap-6 lg:grid-cols-2">
      <Section id="finance-compliance" icon={Landmark} title="Current financial position"><p className="font-medium text-[#241b20]">Pre-revenue · Product development</p><p className="mt-2 text-sm leading-6">KLPS is progressing through product development toward prototype validation and an initial controlled commercial cohort.</p><dl className="mt-5 grid grid-cols-2 gap-4"><Value label="Founder salary from KLPS" value={pounds(d.currentFinancialPosition.founderSalary)} /><Value label="Employees" value={String(d.currentFinancialPosition.employees)} /><Value label="Manufacturing premises" value={d.currentFinancialPosition.manufacturingPremises} /><Value label="External equity raised" value={pounds(d.currentFinancialPosition.externalEquityRaised)} /></dl><div className="mt-5 rounded-xl bg-pink-50/60 p-4"><h3 className="text-sm font-semibold text-[#241b20]">Finance and compliance basis</h3><p className="mt-2 text-sm leading-6">{d.financeAndCompliance}</p></div></Section>
      <Section icon={Banknote} title="Funding activity"><Status label="SEIS preparation" status={d.funding.seis.status} text="Investment-readiness and SEIS preparation underway ahead of the company's first external equity raise." /><Status label="Start Up Loan" status={d.funding.startUpLoan.status} text={`£7,000 application supporting defined product-development expenditure and prototype progression. ${d.funding.startUpLoan.statement}`} /><Status label="Equity fundraising" status={d.funding.equityRaise.status} text={d.funding.equityRaise.statement} /></Section>
    </section>

    <Section id="founding-50" icon={CircleDollarSign} title="Commercial model · Founding 50"><div className="overflow-x-auto"><table className="w-full min-w-[520px] text-left text-sm"><tbody>{[["Initial commercial cohort", `${d.commercialForecast.customers} customers`], ["Forecast revenue", pounds(d.commercialForecast.forecastSales)], ["Estimated direct cost of sales", pounds(d.commercialForecast.forecastDirectCosts)], ["Gross contribution", pounds(d.commercialForecast.forecastGrossContribution)], ["Commercial unit cost assumption", pounds(d.commercialForecast.estimatedDirectCostPerUnit)], ["Introductory price range", d.commercialForecast.introductoryPriceRange]].map(([label, value]) => <tr key={label} className="border-b border-pink-100"><th className="py-3 pr-6 font-medium text-[#71616a]">{label}</th><td className="py-3 font-semibold text-[#241b20]">{value}</td></tr>)}</tbody></table></div><p className="mt-4 text-xs leading-5">{d.commercialForecast.qualification}</p></Section>

    <Section id="twelve-month-forecast" icon={CircleDollarSign} title="12-month financial forecast"><p className="text-sm leading-6">{d.twelveMonthForecast.source}. The schedule below shows the commercial operating extract without presenting pending finance as secured cash.</p><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[900px] text-right text-xs"><thead className="border-b border-pink-100 text-[#9b8993]"><tr><th className="py-3 pr-4 text-left font-medium">Forecast line</th>{d.twelveMonthForecast.periodLabels.map(period => <th key={period} className="p-2 font-medium">{period}</th>)}<th className="p-2 font-semibold text-[#241b20]">Total</th></tr></thead><tbody>{[["Forecast sales", d.twelveMonthForecast.sales, d.commercialForecast.forecastSales], ["Direct cost of sales", d.twelveMonthForecast.directCosts, d.commercialForecast.forecastDirectCosts], ["Gross contribution", d.twelveMonthForecast.grossContribution, d.commercialForecast.forecastGrossContribution]].map(([label, values, total]) => <tr key={String(label)} className="border-b border-pink-100"><th className="py-3 pr-4 text-left font-medium text-[#71616a]">{String(label)}</th>{(values as readonly number[]).map((value, index) => <td key={`${label}-${index}`} className="p-2 text-[#241b20]">{pounds(value)}</td>)}<td className="p-2 font-semibold text-[#241b20]">{pounds(total as number)}</td></tr>)}</tbody></table></div><p className="mt-4 text-xs leading-5">{d.twelveMonthForecast.qualification}</p></Section>

    <Section icon={Banknote} title="Near-term capital deployment"><div className="overflow-x-auto"><table className="w-full min-w-[520px] text-left text-sm"><tbody>{d.useOfFunds.map(row => <tr key={row.item} className="border-b border-pink-100"><td className="py-3 pr-6">{row.item}</td><td className="py-3 text-right font-semibold text-[#241b20]">{pounds(row.amount)}</td></tr>)}<tr className="font-semibold text-[#241b20]"><td className="py-4">Total</td><td className="py-4 text-right">£7,000</td></tr></tbody></table></div><p className="mt-4 text-sm leading-6">This funding is intended to move KLPS through engineering development, prototype iteration and preparation for controlled wearer and commercial testing. It does not fund founder salary.</p><div className="mt-5 rounded-xl border border-amber-200 bg-amber-50/70 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-semibold text-[#241b20]">Ignitec proposal 915</h3><span className="rounded-full border border-amber-200 bg-white px-2.5 py-1 text-[10px] font-medium uppercase tracking-wider text-amber-900">Not accepted</span></div><p className="mt-2 text-sm leading-6">{d.engineeringProposal.scope}</p><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2 lg:grid-cols-4"><Value label="Net fee" value={pounds(d.engineeringProposal.netFee)} /><Value label="VAT" value={pounds(d.engineeringProposal.vat)} /><Value label="Cash required" value={pounds(d.engineeringProposal.grossCashRequirement)} /><Value label="Payment" value={d.engineeringProposal.paymentTerms} /></dl><p className="mt-4 text-xs leading-5">The £2,550 allocation is the net proposal fee. The quoted invoice would be £3,060 including VAT. VAT recovery remains subject to the normal rules; the gross amount is the immediate cash requirement. {d.engineeringProposal.correction}</p><p className="mt-3 text-xs font-medium leading-5 text-[#241b20]">Decision gate: {d.engineeringProposal.decisionGate}</p><Link className="mt-4 inline-flex items-center gap-1 text-sm font-medium text-[#9d245d] underline decoration-pink-200 underline-offset-4" to="/data-room?folder=Development%20Conversations">Review the Ignitec engagement record <ArrowUpRight size={13} /></Link></div></Section>

    <Section icon={ShieldCheck} title="Finance, commercial and product readiness"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{d.readiness.filter(group => ["Finance", "Commercial", "Product"].includes(group.area)).map(group => <div key={group.area} className="rounded-xl border border-pink-100 p-4"><h3 className="font-semibold text-[#241b20]">{group.area}</h3><ul className="mt-3 space-y-3 text-sm">{group.items.map(([label, complete]) => <li key={label} className="flex gap-2">{complete ? <Check size={16} className="mt-0.5 shrink-0 text-emerald-600" /> : <Circle size={14} className="mt-1 shrink-0 text-amber-600" />}<span><span className="block">{label}</span>{readinessLinks[label] && <EvidenceLink {...readinessLinks[label]} />}</span></li>)}</ul></div>)}</div></Section>

    <footer className="rounded-xl border border-pink-100 bg-pink-50/50 p-4 text-xs leading-5"><strong className="text-[#241b20]">Disclosure basis:</strong> {d.disclosureBasis}</footer>
  </article>;
}

function Section({ id, icon: Icon, title, children }: { id?: string; icon: typeof Landmark; title: string; children: React.ReactNode }) { return <section id={id} className="scroll-mt-6 rounded-2xl border border-pink-100 p-6"><h2 className="flex items-center gap-2 font-semibold text-[#241b20]"><Icon size={18} /> {title}</h2><div className="mt-5">{children}</div></section>; }
function EvidenceLink({ href, label }: { href: string; label: string }) { const classes = "mt-1 inline-flex items-center gap-1 font-medium text-[#9d245d] underline decoration-pink-200 underline-offset-4"; return href.startsWith("#") ? <a className={classes} href={href}>{label}<ArrowUpRight size={12} /></a> : <Link className={classes} to={href}>{label}<ArrowUpRight size={12} /></Link>; }
function Metric({ label, value, note, href }: { label: string; value: string; note: string; href?: string }) { const content = <><p className="text-xs uppercase tracking-wider text-[#9b8993]">{label}</p><p className="mt-2 text-2xl font-semibold text-[#241b20]">{value}</p><p className={`mt-1 text-xs ${href ? "text-[#9d245d] underline decoration-pink-200 underline-offset-4" : ""}`}>{note}</p></>; return href ? <a href={href} className="block rounded-xl border border-pink-100 bg-white p-4 transition hover:border-pink-300 hover:shadow-sm focus:outline-none focus:ring-2 focus:ring-pink-300">{content}</a> : <div className="rounded-xl border border-pink-100 bg-white p-4">{content}</div>; }
function Value({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs uppercase tracking-wider text-[#9b8993]">{label}</dt><dd className="mt-1 font-medium text-[#241b20]">{value}</dd></div>; }
function Status({ label, status, text }: { label: string; status: DisclosureStatus; text: string }) { return <div className="mb-3 rounded-xl border border-pink-100 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="text-sm font-semibold text-[#241b20]">{label}</h3><span className={`rounded-full border px-2.5 py-1 text-[10px] font-medium uppercase tracking-wider ${statusStyle[status]}`}>{statusLabel[status]}</span></div><p className="mt-2 text-sm leading-6">{text}</p></div>; }
