import type { Expense, ExpenseDto } from "@/types/expense";

export const mapExpenseDto = (dto: ExpenseDto): Expense => ({
  id: dto.id,
  importKey: dto.import_key,
  name: dto.name,
  supplierName: dto.supplier_name,
  category: dto.category,
  costType: dto.cost_type,
  frequency: dto.frequency,
  transactionDate: dto.transaction_date,
  servicePeriodStart: dto.service_period_start,
  servicePeriodEnd: dto.service_period_end,
  currency: dto.currency,
  netAmount: dto.net_amount,
  creditAdjustment: dto.credit_adjustment,
  vatAmount: dto.vat_amount,
  vatRate: dto.vat_rate,
  grossAmount: dto.gross_amount,
  supplierCostAmount: dto.supplier_cost_amount,
  supplierCostBasis: dto.supplier_cost_basis,
  recurringRunRateNet: dto.recurring_run_rate_net,
  recurringRunRateVatRate: dto.recurring_run_rate_vat_rate,
  klpsAllocationAmount: dto.klps_allocation_amount,
  klpsAllocationPercentage: dto.klps_allocation_percentage,
  currentStatus: dto.current_status,
  paidBy: dto.paid_by,
  paymentChannel: dto.payment_channel,
  reimbursementStatus: dto.reimbursement_status,
  companyCashOutflow: dto.company_cash_outflow,
  businessExpenseStatus: dto.business_expense_status,
  evidenceStatus: dto.evidence_status,
  evidenceReference: dto.evidence_reference,
  evidenceId: dto.evidence_id,
  notes: dto.notes,
  metadata: dto.metadata,
  updatedAt: dto.updated_at,
  version: dto.version,
  changeReason: dto.change_reason,
});
