import { formatVatPeriodLabel } from "../../lib/vat-ledger-ui.ts";
import type { VatLedgerRow,VatPeriod } from "../../types/vat-ledger.ts";

export const VAT_WORKING_PAPER_LABEL="VAT working paper – not an HMRC submission";
export const vatExportColumns=["Expense ID","Tax-point date","Invoice date","Payment date","Supplier","Supplier country","Supplier VAT number","Invoice number","Payment reference","Description","Category","Currency","Foreign gross","Exchange rate","GBP net","GBP VAT","GBP gross","VAT rate","VAT treatment","Business-use percentage","Recoverable VAT","Founder paid","Reimbursement status","Evidence coverage","Evidence filenames or IDs","Review status","VAT period","Notes","Created date","Last updated date","Stored VAT period","Effective VAT period","Period source","Effective tax-point date"];
export const vatExportValues=(r:VatLedgerRow)=>[r.id,r.transaction_date,r.invoice_date,r.payment_date,r.supplier_name,r.supplier_country,r.supplier_vat_number,r.invoice_number,r.order_reference,r.description??r.name,r.category,r.currency,r.gross_amount,r.exchange_rate,r.gbp_net_amount,r.gbp_vat_amount,r.gbp_gross_amount,r.vat_rate,r.vat_treatment,r.business_use_percentage,r.recoverable_vat_amount,r.founder_paid,r.reimbursement_status,r.evidence_coverage??r.evidence_status,(r.evidence_files??[]).map(e=>e.filename??e.id).join("; "),r.vat_review_status,r.vat_period_start&&r.vat_period_end?formatVatPeriodLabel({start_date:r.vat_period_start,end_date:r.vat_period_end}):"",r.notes,r.created_at,r.updated_at,r.stored_vat_period_id,r.effective_vat_period_id,r.vat_period_source,r.effective_tax_point_date];
const download=(blob:Blob,name:string)=>{const u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),60_000);};
export const buildVatCsv=(rows:VatLedgerRow[])=>{const quote=(v:unknown)=>`"${String(v??"").replace(/"/g,'""')}"`;return[[VAT_WORKING_PAPER_LABEL],vatExportColumns,...rows.map(vatExportValues)].map(r=>r.map(quote).join(",")).join("\n");};
export const vatReviewSummaryRows=(rows:VatLedgerRow[],period?:VatPeriod)=>{const total=(key:keyof VatLedgerRow)=>rows.reduce((n,r)=>n+Number(r[key]??0),0);return[[VAT_WORKING_PAPER_LABEL],["Period",period?formatVatPeriodLabel(period):"All periods"],["Transaction count",rows.length],["Total gross",total("gbp_gross_amount")],["Total VAT entered",total("gbp_vat_amount")],["Total recoverable VAT",total("recoverable_vat_amount")],["Transactions with no supplier invoice",rows.filter(r=>!(r.evidence_files??[]).some(e=>e.type?.includes("invoice"))).length],["Payment-evidence-only transactions",rows.filter(r=>(r.evidence_files??[]).length>0&&(r.evidence_files??[]).every(e=>e.type?.includes("payment"))).length],["Foreign-currency transactions",rows.filter(r=>r.currency!=="GBP").length],["Reverse-charge review items",rows.filter(r=>r.vat_treatment==="reverse_charge_review_required").length],["Personal or mixed-use items",rows.filter(r=>Number(r.business_use_percentage??1)<1).length],["Refunds and credits","See adjustment records"],["Unresolved warnings",rows.reduce((n,r)=>n+(r.warnings??[]).length,0)]];};
export const exportVatCsv=(rows:VatLedgerRow[])=>download(new Blob([buildVatCsv(rows)],{type:"text/csv;charset=utf-8"}),"KLPS-VAT-working-ledger.csv");
export async function buildVatWorkbook(rows:VatLedgerRow[],period?:VatPeriod){const {default:ExcelJS}=await import("exceljs");const wb=new ExcelJS.Workbook();const ledger=wb.addWorksheet("Working ledger");ledger.addRow([VAT_WORKING_PAPER_LABEL]);ledger.mergeCells(1,1,1,vatExportColumns.length);ledger.getCell(1,1).font={bold:true};ledger.addRow(vatExportColumns);rows.forEach(r=>ledger.addRow(vatExportValues(r)));ledger.views=[{state:"frozen",ySplit:2}];ledger.autoFilter={from:{row:2,column:1},to:{row:2,column:vatExportColumns.length}};wb.addWorksheet("Review summary").addRows(vatReviewSummaryRows(rows,period));return wb;}
export async function exportVatXlsx(rows:VatLedgerRow[],period?:VatPeriod){const wb=await buildVatWorkbook(rows,period);const buffer=await wb.xlsx.writeBuffer();download(new Blob([buffer],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"}),"KLPS-VAT-working-ledger.xlsx");}
