name: Build and Deploy

on:
  push:
    branches:
      - main  

jobs:
  build-deploy:
    runs-on: ubuntu-22.04  

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  

      - name: Install and Build
        run: |
          npm ci  # Clean install dependencies
          npm run build  

      - name: Deploy to Server
        uses: burnett01/rsync-deployments@v1
        with:
          switches: -avz --delete
          path: ./build/
          remote_path: /var/www/klps.co.uk/build
          remote_host: 167.71.133.117
          remote_user: root
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
