name: Deploy to Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Add Droplet Host to Known Hosts
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DROPLET_HOST_KEY }}" >> ~/.ssh/known_hosts

    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: 167.71.133.117
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/klps.co.uk
          if [ -d .git ]; then
            git reset --hard HEAD
            git pull origin main
          else
            git clone https://github.com/KLPS-IO/Website-UX-UI.git .
          fi
          sudo systemctl restart apache2
